### ISSUE TITLE
Strategy to discourage old CWOP posts

### ISSUE THREAD

**Issue by tkeffer** [weewx/weewx#106]
Because CWOP timestamps incoming records with the wall clock time, any catchup will result in a bunch of older records looking like new records.

Either change `stale` to something smaller, maybe 60 seconds, or not allow old records at all.

**Comment by matthewwall** [comment]
set stale to 60 seconds. fixed at 2091be1..f935d2b

**Comment by jcea** [comment]
I think that 60 seconds is overkill. 1800 was OK, 900 could be appropriate. 60 seconds is unusable in my situation :-). I have added a explicit "stale=900" in my configuration to cope with this change.

Related: PR #277
