### ISSUE TITLE
vantage station went away, causing weewx to exit

### ISSUE THREAD

**Issue by matthewwall** [weewx/weewx#134]
got this exception a few days ago, but did not notice it until today (2 days later) when people started asking why the weather pages were 2 days old.

Jun 22 17:29:30 sailing weewx[32197]: vantage: SerialException.
Jun 22 17:29:30 sailing weewx[32197]:    ****  device reports readiness to read but returned no data (device disconnected?)
Jun 22 17:29:30 sailing weewx[32197]:    ****  Is there a competing process running??
Jun 22 17:29:30 sailing weewx[32197]: vantage: LOOP try #1; error: device reports readiness to read but returned no data (device disconnected?)
Jun 22 17:29:30 sailing weewx[32197]: engine: Shutting down StdReport thread
Jun 22 17:29:30 sailing weewx[32197]: engine: Caught unrecoverable exception in engine:
Jun 22 17:29:30 sailing weewx[32197]:     ****  write failed: [Errno 5] Input/output error
Jun 22 17:29:31 sailing weewx[32197]:     ****  Traceback (most recent call last):
Jun 22 17:29:31 sailing weewx[32197]:     ****    File "/opt/weewx-3.5.0/bin/weewx/engine.py", line 873, in main
Jun 22 17:29:31 sailing weewx[32197]:     ****      engine.run()
Jun 22 17:29:31 sailing weewx[32197]:     ****    File "/opt/weewx-3.5.0/bin/weewx/engine.py", line 185, in run
Jun 22 17:29:31 sailing weewx[32197]:     ****      for packet in self.console.genLoopPackets():
Jun 22 17:29:31 sailing weewx[32197]:     ****    File "/opt/weewx-3.5.0/bin/weewx/drivers/vantage.py", line 491, in genLoopPackets
Jun 22 17:29:31 sailing weewx[32197]:     ****      for _loop_packet in self.genDavisLoopPackets(200):
Jun 22 17:29:31 sailing weewx[32197]:     ****    File "/opt/weewx-3.5.0/bin/weewx/drivers/vantage.py", line 511, in genDavisLoopPackets
Jun 22 17:29:31 sailing weewx[32197]:     ****      self.port.wakeup_console(self.max_tries)
Jun 22 17:29:31 sailing weewx[32197]:     ****    File "/opt/weewx-3.5.0/bin/weewx/drivers/vantage.py", line 72, in wakeup_console
Jun 22 17:29:31 sailing weewx[32197]:     ****      self.write('\n')
Jun 22 17:29:31 sailing weewx[32197]:     ****    File "/opt/weewx-3.5.0/bin/weewx/drivers/vantage.py", line 268, in write
Jun 22 17:29:31 sailing weewx[32197]:     ****      N = self.serial_port.write(data)
Jun 22 17:29:31 sailing weewx[32197]:     ****    File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 485, in write
Jun 22 17:29:31 sailing weewx[32197]:     ****      raise SerialException('write failed: %s' % (v,))
Jun 22 17:29:31 sailing weewx[32197]:     ****  SerialException: write failed: [Errno 5] Input/output error
Jun 22 17:29:31 sailing weewx[32197]:     ****  Exiting.

this might have been caused by someone disconnecting the vantage from the computer (it is connected via usb).  or it might have been some spurious serial hiccup.  i'm creating an issue about this because i'd like weewx to recover nicely from this (e.g., reload the driver after 60 seconds) instead of bailing out.  i do not have time to think about or make a fix at the moment - just putting the issue in the queue...

**Comment by tkeffer** [comment]
Fixed in commit 0275d49f3d47558978d6f5cc40b03b5b5e1badf3
