### ISSUE TITLE
Please change extraSensors numbering in wmr200.py

### ISSUE THREAD

**Issue by holzinet** [weewx/weewx#14]
I have changed my weatherstation from wmr100 to wmr200 and have recognized a little difference/inconsistency.
While at wmr100.py the numbering for extra sensors starts at 1 (extraTemp1, extraHumid1),
the wmr200.py driver starts the numbering at 2 for extra sensor no.1 (at channel 2).
So you have to update your sql-columns with
UPDATE archive SET extraTemp3 = extraTemp2
UPDATE archive SET extraTemp2 = extraTemp1
and so on.

At wmr100.py the channel-number is subtracted with 1 - "channel-1":
...
            _record['extraTemp%d'  % (channel-1)] = T
            _record['extraHumid%d' % (channel-1)] = R
...

So, if you would change at lines 1041,1042
            record['extraTemp%d' % sensor_id] = temp
            record['extraHumid%d' % sensor_id] = humidity
to
            record['extraTemp%d' % (sensor_id-1)] = temp
            record['extraHumid%d' % (sensor_id-1)] = humidity
the wmr200 driver would be "compatible" to the wmr100 driver in this way and if you don't have to update the database, if you switch from wmr100 to wmr200.
To update an existing WMR200 database, you could do with the sql commands:
UPDATE archive SET extraTemp1 = extraTemp2
UPDATE archive SET extraTemp2 = extraTemp3
...

**Comment by tkeffer** [comment]
Hello,

I get your point, but if we change this, we will change it for *all* WMR200 users. All of a sudden, their formerly working system will stop working.

It's best that we treat these as two separate instruments, which use two separate numbering schemes for their sensors.

If you don't like this, you can always add a simple service that simply renames the numbers. Something like (NOT TESTED):
```python
import weewx
from weewx.engine import StdService

class Switch(StdService):
    
    def __init__(self, engine, config_dict):
        # Initialize my base class:
        super(Switch, self).__init__(engine, config_dict)
            
        self.bind(weewx.NEW_LOOP_PACKET, self.new_loop_packet)
        self.bind(weewx.NEW_ARCHIVE_RECORD, self.new_archive_record)
            
    def new_loop_packet(self, event):
        event.packet['extraTemp1'] = event.packet.pop('extraTemp2', None)

    def new_archive_record(self, event):
        event.record['extraTemp1'] = event.record.pop('extraTemp2', None)
```
