### ISSUE TITLE
consider aggregation_type of max for radiation and uv

### ISSUE THREAD

**Issue by matthewwall** [weewx/weewx#143]
one could argue that the plots for solar radiation and uv are more useful when they show the maximum value, not the average value.

https://groups.google.com/forum/#!topic/weewx-user/auZ7lzrQDvA

although liz pointed this out specifically for month and year, it probably applies to every time period.

**Comment by tkeffer** [comment]
Why not both?

**Comment by matthewwall** [comment]
added max to radiation and uv plots at commit 612873e
