### ISSUE TITLE
Implement a $time_ago tag

### ISSUE THREAD

**Issue by matthewwall** [weewx/weewx#16]
Implement a $time_ago, or $timespan tag (see email with Gary Roderick).

(from the TODO file)

**Comment by tkeffer** [comment]
I assume the new tag `$span` satisfies this. Closing issue. If not, we can reopen.

**Comment by gjr80** [comment]
Hard to say but I think between the tag $span (for aggregates) and the undocumented (I think it is still undocumented) $timestamp parameter in the tag $current (eg $current($timestamp=$now-300).outTemp (for point in time values)) all of the 'ago' tags I was after have been implemented.
