### ISSUE TITLE
default DB schema has extraTemp1 to 3, but only extraHumid1 and 2

### ISSUE THREAD

**Issue by mdecker** [weewx/weewx#165]
The current default database schema contains columns for three extra temperature values (extraTemp1 to 3) but only for two extra humidity values (extraHumid1 and 2).
At least on the WMR200 the extra temperature sensors are coupled with humidity sensors. I have no idea if this is the case for other weather stations as well, but I think it would make sense to think about a third extra humidity value in the default schema.
What do you think?

**Comment by tkeffer** [comment]
The current default schema was inherited from wview.

I doubt very many weather stations require more than two humidity values. Is this your situation? If so, adding new columns to the default schema would not help you unless you are a new user. If you are a new user, why not just add the columns you need before you fire up your station for the first time?

In any case, this overlaps with Issue #115.
