### ISSUE TITLE
Make setup.py do nicer formatting to weewx.conf

### ISSUE THREAD

**Issue by matthewwall** [weewx/weewx#18]
- spacing before when injecting skin stanzas
  - spacing before when injecting database and binding stanzas
  - spacing before when injecting restful stanzas
  - rows of hashmarks when injecting service stanzas such as [Forecast]
  - inject service stanzas somewhere other than end of file
  - inject skin stanzas before ftp and rsync

**Comment by tkeffer** [comment]
This has been fixed in V3.2. Closing issue.
