### ISSUE TITLE
Weewx not working after update

### ISSUE THREAD

**Issue by DaveJ61** [weewx/weewx#184]
Hi,
My weewx has been running great for a couple of years on my ubuntu server 14.04LTS and so I thought it was time to update the owfs to 3.1p4 and weewx to 3.6.2. The updates went fairly swimmingly but when I try and start weewx, I get this mess in the syslog:-

> Nov 27 12:31:15 localhost weewx[23208]: engine: Initializing weewx version 3.6.2
Nov 27 12:31:15 localhost weewx[23208]: engine: Using Python 2.7.6 (default, Jun 22 2015, 17:58:13) #012[GCC 4.8.2]
Nov 27 12:31:15 localhost weewx[23208]: engine: Platform Linux-3.13.0-88-generic-x86_64-with-Ubuntu-14.04-trusty
Nov 27 12:31:15 localhost weewx[23208]: engine: pid file is /var/run/weewx.pid
Nov 27 12:31:15 localhost weewx[23212]: engine: Using configuration file /etc/weewx/weewx.conf
Nov 27 12:31:15 localhost weewx[23212]: engine: Loading station type OWFS (user.owfs)
Nov 27 12:31:15 localhost weewx[23212]: engine: Caught unrecoverable exception in engine:
Nov 27 12:31:15 localhost weewx[23212]:     ****  libow-3.1.so.4: cannot open shared object file: No such file or directory
Nov 27 12:31:15 localhost weewx[23212]:     ****  Traceback (most recent call last):
Nov 27 12:31:15 localhost weewx[23212]:     ****    File "/usr/share/weewx/weewx/engine.py", line 841, in main
Nov 27 12:31:15 localhost weewx[23212]:     ****      engine = engine_class(config_dict)
Nov 27 12:31:15 localhost weewx[23212]:     ****    File "/usr/share/weewx/weewx/engine.py", line 70, in __init__
Nov 27 12:31:15 localhost weewx[23212]:     ****      self.setupStation(config_dict)
Nov 27 12:31:15 localhost weewx[23212]:     ****    File "/usr/share/weewx/weewx/engine.py", line 94, in setupStation
Nov 27 12:31:15 localhost weewx[23212]:     ****      __import__(driver)
Nov 27 12:31:15 localhost weewx[23212]:     ****    File "/usr/share/weewx/user/owfs.py", line 166, in <module>
Nov 27 12:31:15 localhost weewx[23212]:     ****      import ow
Nov 27 12:31:15 localhost weewx[23212]:     ****    File "/usr/lib/python2.7/dist-packages/ow/__init__.py", line 33, in <module>
Nov 27 12:31:15 localhost weewx[23212]:     ****      from ow import _OW
Nov 27 12:31:15 localhost weewx[23212]:     ****  ImportError: libow-3.1.so.4: cannot open shared object file: No such file or directory
Nov 27 12:31:15 localhost weewx[23212]:     ****  Exiting.

My owfs is actually located in opt/owfs as it is compiled to the latest version. The latest on offer through Ubuntu is only 2.9 and I believe this does not support the new Hobbyboards barometer.

I can actually get weewx to run if I set the driver to Simulated.

I would appreciate some assistance in getting my weather station running again.

**Comment by tkeffer** [comment]
Hello, Dave

The issues list is for bugs in weewx. This sounds more like a support question about installing an extension on your system. Please direct your question to the [weewx support group](https://groups.google.com/forum/#!forum/weewx-user).
