### ISSUE TITLE
WMR200 Extra Sensors Renumbered with latest release of weewx

### ISSUE THREAD

**Issue by bjs-pdx** [weewx/weewx#191]
I just upgraded my system to weewx 3.6.2 yesterday and now find I have a problem with the data being captured from my wmr200 weather station.  I added two additional temperature sensors as extratemp2 and extratemp3 which were working before the upgrade.  One of the sensors is temporarily offline, extratemp2.  Now, weewx thinks that extratemp3 is extratemp2.  I didn't make any configuration changes, only updated the system using the old config an skin files.

Any idea what happened or how to fix it?  Does it just read the extra temperature settings in order, which may be a problem with one offline, or are they tied to the data sent from the station based on assigned sensor numbers?

**Comment by tkeffer** [comment]
Hello.

The issues list is for bug reports. Yours is a support question. Please post it to the [weewx-user group](https://groups.google.com/forum/#!forum/weewx-user).
