### ISSUE TITLE
Doing 'setup.py install --extension' should prompt for required parameters

### ISSUE THREAD

**Issue by matthewwall** [weewx/weewx#21]
in v3.1 the behavior is to inject required parameters
   into weewx.conf.  for passwords and tokens, inject INSERT_XXX_HERE.  when
   service starts up, detect missing or default passwords/tokens and bail out
   with a log message (as the restful services do).

if the installer prompts for the parameters required by an extension then user would not have to do the extra step of modifying the configuration file.

**Comment by tkeffer** [comment]
Can we closet this one out?

**Comment by matthewwall** [comment]
one way to do this would be to add methods to the ExtensionInstaller class analogous to the methods on the AbstractConfEditor:

default_stanza
get_conf
prompt_for_settings

default_stanza and get_conf are not really appropriate for extensions - a single extension might have multiple config stanzas, not just one.  they work for a driver, since it will only ever have one stanza.
