### ISSUE TITLE
Update documentation to state python-mysqld is required

### ISSUE THREAD

**Issue by kathode** [weewx/weewx#211]
Hi,

First of all, thanks for weewx, it is really useful!

I'm running version 3.6.2 on Raspbian/Jessie on a Raspberry Pi 3 using the very useful weewx-sdr driver.

Now, I've had plenty of issues with the sqlite database being locked ([*I'm aware you are aware](http://weewx.com/docs/usersguide.htm#spikes)), so I've decided to migrate my database over to MySQL. Promptly I followed the [Transfer from sqlite to MySQL guide](https://github.com/weewx/weewx/wiki/Transfer-from-sqlite-to-MySQL), however no matter how I changed the settings for my MySQL server, including database name, account name and whatnot, I constantly failed at transferring the data:

```
pi@framboesa:/etc/mysql $ wee_database --transfer --dest-binding=dest_binding
Using configuration file /etc/weewx/weewx.conf
Using database binding 'wx_binding', which is bound to database 'archive_sqlite'
Transfer 40871 records from source database 'weewx.sdb' to destination database 'weewx' (y/n)? y
Error accessing destination database 'weewx'.
Maybe the database driver is incorrectly specified in weewx.conf?
Nothing done. Aborting.
```

May I suggest that the above error message be updated to provide more details? I looked into the source code, but could not really figure out what could be wrong at that point, but simply that wee_database never got past lines [406-408](https://github.com/weewx/weewx/blob/master/bin/wee_database#L406-L408).

I then looked into extended logging for MySQL by enabling the following options 
```
general_log_file        = /var/log/mysql/mysql.log
general_log             = 1
```
It was only at this point that by examining the logfile I concluded that no connection was being attempted at all. I then played with wee_database and stumbled upon the following trace:

```
pi@framboesa:/etc/mysql $ wee_database --create-archive --binding=dest_binding --dry-run
Using configuration file /etc/weewx/weewx.conf
Using database binding 'dest_binding', which is bound to database 'archive_mysql'
Traceback (most recent call last):
  File "/usr/bin/wee_database", line 453, in <module>
    main()
  File "/usr/bin/wee_database", line 156, in main
    createMainDatabase(config_dict, db_binding)
  File "/usr/bin/wee_database", line 179, in createMainDatabase
    with weewx.manager.open_manager_with_config(config_dict, db_binding) as dbmanager:
  File "/usr/share/weewx/weewx/manager.py", line 984, in open_manager_with_config
    return open_manager(manager_dict, initialize)
  File "/usr/share/weewx/weewx/manager.py", line 976, in open_manager
    manager_dict['table_name'])
  File "/usr/share/weewx/weewx/manager.py", line 99, in open
    connection = weedb.connect(database_dict)
  File "/usr/share/weewx/weedb/__init__.py", line 60, in connect
    __import__(db_dict['driver'])
  File "/usr/share/weewx/weedb/mysql.py", line 10, in <module>
    import MySQLdb
ImportError: No module named MySQLdb
```

At this point I had my answer, no such python module was installed in this system. Simple and clear. However nowhere in the **[Transfer from sqlite to MySQL guide](https://github.com/weewx/weewx/wiki/Transfer-from-sqlite-to-MySQL) nor in the [user guide](http://weewx.com/docs/usersguide.htm) is it stated that the MySQL module for python needs to be present if using MySQL. Perhaps a suggestion to check it is installed would have been enough :-)

**I edited the page [Transfer from sqlite to MySQL guide](https://github.com/weewx/weewx/wiki/Transfer-from-sqlite-to-MySQL) to state that the MySQL python module is required.

**Comment by tkeffer** [comment]
Thanks for your good sleuthing!

Fixed in commit https://github.com/weewx/weewx/commit/d7a7913cc89bab7b392cd16b909321451e931f8d
