### ISSUE TITLE
getting openweathermap station_id

### ISSUE THREAD

**Issue by paolobenve** [weewx/weewx#215]
Hi! I registered on openweathermap, I got a key, but I cannot realize how can I get a station_id in order to put it in weewx.con as explained in https://github.com/weewx/weewx/wiki/openweathermap

Any hint is appreciated.

**Comment by tkeffer** [comment]
Please post your question to the [weewx-user group](https://groups.google.com/forum/#!forum/weewx-user). This website is for bug tracking.
