### ISSUE TITLE
Wrong Installation Folder

### ISSUE THREAD

**Issue by noxx2015** [weewx/weewx#221]
hi

i had installed weewx via tar file. with this, weewx is installed in /home/weewx
if i use the forecast installer, the "addon" install in /etc/weewx

how can i change this now?

**Comment by matthewwall** [comment]
how did you install the forecast extension?

**Comment by tkeffer** [comment]
Hello,

This issues list is for reporting and tracking bugs, not for support questions. Please direct your question to the [weewx-user group](https://groups.google.com/forum/#!forum/weewx-user).
