### ISSUE TITLE
owfs.py: pre-empts  ignore_zero_wind setting in weewx.conf

### ISSUE THREAD

**Issue by glennmckechnie** [weewx/weewx#222]
Setting 'ignore_zero_wind = False'  in the [StdWXCalculate] section of weewx.conf has no affect on the output as the calculation has already been performed within the owfs driver.

Treat as redundant?

DRIVER_NAME = 'OWFS'
DRIVER_VERSION = "0.19"

at line 455...
 
     def calculate_derived(self, data):
        if 'windSpeed' in data:
            if data['windSpeed'] is None or data['windSpeed'] == 0:
                data['windDir'] = None

**Comment by matthewwall** [comment]
fixed in owfs 0.20

thanks for finding that!
