### ISSUE TITLE
adopt a cheetah

### ISSUE THREAD

**Issue by matthewwall** [weewx/weewx#223]
the cheetah documentation has been unavailable for some time now (since late 2016?)

we should see about hosting the cheetah docs at weewx.com

**Comment by tkeffer** [comment]
I agree.

I wish someone would take ownership of the project. I really don't want to, but it's an incredibly valuable piece of software. I'll w rite rtyler and ask his intentions.

**Comment by awcolley** [comment]
Is this not the current documentation? https://pythonhosted.org/Cheetah/users_guide/index.html

Or is this a fork of the Cheetah used in weewx?

I was using this earlier today and what I learned there worked in weewx (though I didn't go very wide or deep in Cheetah).

**Comment by matthewwall** [comment]
there were a couple of references to cheetahtemplate.org in the weewx docs.  these have been replaced with the pythonhosted.org url as of commit 9b37e15

**Comment by tkeffer** [comment]
> Is this not the current documentation? https://pythonhosted.org/Cheetah/users_guide/index.html

It is, and there seems to be more information there than the last time I looked, but perhaps my memory is faulty.

I've had an exchange with the original Cheetah author. He passed the code on to someone else, who seems to be disengaged. There are other groups in a similar situation. If someone in the weewx community wanted to take Cheetah over, the original author is very willing to pass it on.

**Comment by tkeffer** [comment]
The link to the pythonhosted documentation will serve for now. Closing, but we can reopen if someone has an interest in taking on Cheetah. I don't.
