### ISSUE TITLE
Permit the user to personalize the x-grid

### ISSUE THREAD

**Issue by paolobenve** [weewx/weewx#225]
x grid plot interval is hard-coded at https://github.com/weewx/weewx/blob/master/bin/weeplot/utilities.py in function scaletime: it chooses a given interval according to the min and max passed as arguments

I'd like to be able to bypass this function by an x-interval similar to the 3rd value of the yscale 3-way tuple

A user-given value for x-interval could bypass the interval calculation that the code now performs.

**Comment by tkeffer** [comment]
How about a Pull Request?

**Comment by paolobenve** [comment]
I made it, maybe the docs and website patch is missing, but it's an easy task
