### ISSUE TITLE
color or fill_color?

### ISSUE THREAD

**Issue by paolobenve** [weewx/weewx#227]
https://github.com/weewx/weewx/blob/master/bin/weeplot/genplot.py line 563

`self.fill_color  = color`

is it a bug? should it be replaced with

`self.fill_color  = fill_color`

?

**Comment by tkeffer** [comment]
I believe you're right. That bug has been sitting there for four years!

**Comment by tkeffer** [comment]
Hang on. It's not quite so simple. There is no parameter `fill_color`, so that has to be passed into the initializer for `PlotLine`.

Commit https://github.com/weewx/weewx/commit/2bbe581f0883675a08aaa1ce3cf0fc2d77ffa74a
