### ISSUE TITLE
daily temperatures hourly average not working

### ISSUE THREAD

**Issue by paolobenve** [weewx/weewx#229]
I'm trying to implement the example given in the Customizing guide in the section "Including the same SQL type more than once in a plot":

```
[[[daytemp_with_avg]]]
    [[[[avgTemp]]]]
        data_type = outTemp
        aggregate_type = avg
        aggregate_interval = 3600
        label = Avg. Temp.
    [[[[outTemp]]]]
```

but it only produces the temperature plot, not the average one:

![daytempavg](https://cloud.githubusercontent.com/assets/1417508/23855642/c02c00e0-07f6-11e7-8930-986cf6aca313.png)

**Comment by tkeffer** [comment]
The plot is working properly. If you look closely, you'll see red dots on the hour boundaries.

Your value for `line_gap_fraction` is too small. Try 0.1.

**Comment by paolobenve** [comment]
ok, let me try

but shouldn't the average value be plotted along all the period it refers to, in order to plot something like a line?
