### ISSUE TITLE
ENHANCEMENT: locate avg values in the middle of the period rather than at its end

### ISSUE THREAD

**Issue by paolobenve** [weewx/weewx#231]
Now average values are plotted at the end of the time period they refer to.

I think it would be better to plot them at the middle of that time interval.

**Comment by tkeffer** [comment]
Is this causing a problem for you? You might think temperature should be plotted for the middle of the time interval, but what of total rain? It should clearly be plotted at the end. 

As always, Pull Requests are welcome, but it's not clear what problem we're trying to solve...
