### ISSUE TITLE
Setting Weathercloud interval

### ISSUE THREAD

**Issue by wvanbreukelen** [weewx/weewx#24]
Is it possible to set a specific time interval for uploading data to the weathercloud site?
By the way, i used the plugin, made by Matthew Wall

**Comment by alco28** [comment]
hi, please ask that kind of questions in our forum board https://groups.google.com/forum/#!forum/weewx-user , much faster replies and it's not a issue question for the weewx core application.

**Comment by wvanbreukelen** [comment]
Oh, sorry. Thank you
