### ISSUE TITLE
WMR200 Pressure reading

### ISSUE THREAD

**Issue by kc5ddg** [weewx/weewx#242]
Just trying to figure out what setting I am missing for getting Wunderground to show my pressure reading. It is using the sensor that came with the station. Works fine in Windows so I know the sensor works just not getting an output to Wunderground.

**Comment by tkeffer** [comment]
The issue list is for reporting and tracking bugs. Yours is a support issue. Please direct it to the [weewx-user](https://groups.google.com/forum/#!forum/weewx-user) group.
