### ISSUE TITLE
incorrect color of label for bar graphs

### ISSUE THREAD

**Issue by paolobenve** [weewx/weewx#245]
I have in my skin:

```
        [[[dayrain]]]
            yscale = None, None, 0.02
            plot_type = bar
            [[[[hourlyrain]]]]
                data_type = rain
                aggregate_type = sum
                aggregate_interval = 3600
                label = Pioggia oraria
                fill_color = red
            [[[[dailyrain]]]]
                data_type = rain
                aggregate_type = sum
                aggregate_interval = 86400 # 1 giorno
                label = Pioggia giorn.
                fill_color = blue

```

In the graph the two top labels, "Pioggia oraria" and "Pioggia giorn." had apparently wrong color: blue for the first, red for the second

The reason is that the color used for the label isn't the fill one, but the line one, which is used for the contour line of the bars. In my case the line color isn't set, and then the default color are used, which are blue and red, and their respective order is independent of the fill color.

I think the fill color and not the line one should be used for the labels.

I think I'm able to produce a pull request

**Comment by tkeffer** [comment]
This is a matter of personal preference. Either way can be done using appropriate options.
