### ISSUE TITLE
 Radio Frequency on WMR300 anemometer (Stop receiving by driver)

### ISSUE THREAD

**Issue by runahue** [weewx/weewx#254]
Hello friends.

I am having serious radio frequency interferences on wmr300 anemometer.

I have tried all kind of hardware solutions without good results. 

Interferences are from my own ham radio hf transceiver.

I want try "mute wind data logging" by request.
I think I must modifi wmr300 driver, but I am not sure and my programming knowing is very low.
Please... could you help me?

I can send transmission  status to wmr300 driver by different ways: serial, tcp, etc...

I need only ignore these loop packets while my radio is txing. 

Could I do this?

Tnx a lot

**Comment by tkeffer** [comment]
This is not really a "bug" in weewx --- it's a feature request. It's also a pretty low priority so it's unlikely to happen.

A pull request is always welcome.
