### ISSUE TITLE
make it possible to disable archive_services but keep restful_services

### ISSUE THREAD

**Issue by hayden-t** [weewx/weewx#255]
Hi, i run on a router, so not much space. After a while the sqlite2 db gets big and would eventually fill my space. I only use my wmr200 setup for submitting to wunderground. 

I tried disabling archive_services, but this seems to disable restful_services too, i suppose it needs somewhere to keep the partial records, till it has a full one for submission ?

It would be good if this db size could be limited to minimum needed.

Thanks.

**Comment by tkeffer** [comment]
Unfortunately, the database is needed for the Weather Underground upload. This is because the WU requires a few specialized queries. In particular, total rain for the last hour.

You could run a regular cron job that trims the database.
