### ISSUE TITLE
add footer with warning message (Disclaimer of liability) in weewx standard template

### ISSUE THREAD

**Issue by yannick56** [weewx/weewx#256]
Hello 

Can you add a footer at the bottom of the weewx web pages for standard template with this warning message or something like this :
"Please note that the weather data published on this website are derived from a personal weather station and are given for information only and can not be used to guarantee the protection of persons or property of any kind." ?

Thank you.

**Comment by tkeffer** [comment]
That is easy enough for a user to add.
