### ISSUE TITLE
No current humidity graph or, dayhumidity.png displayed..

### ISSUE THREAD

**Issue by jtx99** [weewx/weewx#262]
The .png is being created by the software, but its not being displayed on index.html

I checked the skin.conf and it shows the dayhumidity string.

Is there something I am missing?  Or possibly, does the software not create this change in the html more than once a day in the index.html?

**Comment by tkeffer** [comment]
This is a support question. Please direct it to the [support forum](https://groups.google.com/forum/#!forum/weewx-user).
