### ISSUE TITLE
Weewx with forecast

### ISSUE THREAD

**Issue by Blisk** [weewx/weewx#275]
How can I put a foreast to weewx, like it is on console? Clouds, sun, rain
I hope in future it will be possible to have a weather forecast for fev days on weewx, calculated by parameters from weather station or pulled from some weather website.

**Comment by tkeffer** [comment]
This issues list is for tracking bugs in weewx. Please direct your query to the [weewx-user](https://groups.google.com/forum/#!forum/weewx-user) group.
