### ISSUE TITLE
CSV Exension v0.9 errors while starting

### ISSUE THREAD

**Issue by vdirienzo** [weewx/weewx#281]
i have installed 0.9v on the server and the following errors are shown when this version pluggin is installed.  On version 0.8v Data is gathered with ought any issue

Source: https://github.com/weewx/weewx/wiki/csv

Oct 17 09:27:20 raspberrypi weewx[1904]: engine: Caught unrecoverable exception in engine:
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****  global name 'dtstr' is not defined
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****  Traceback (most recent call last):
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****    File "/usr/share/weewx/weewx/engine.py", line 871, in main
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****      engine.run()
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****    File "/usr/share/weewx/weewx/engine.py", line 190, in run
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****      self.dispatchEvent(weewx.Event(weewx.NEW_LOOP_PACKET, packet=packet))
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****    File "/usr/share/weewx/weewx/engine.py", line 223, in dispatchEvent
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****      callback(event)
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****    File "/usr/share/weewx/user/csv.py", line 52, in handle_new_loop
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****      self.write_data(event.packet)
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****    File "/usr/share/weewx/user/csv.py", line 77, in write_data
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****      f.write('%s\n' % ','.join(self.sort_data(data)))
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****    File "/usr/share/weewx/user/csv.py", line 91, in sort_data
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****      fields = [dtstr]
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****  NameError: global name 'dtstr' is not defined
Oct 17 09:27:20 raspberrypi weewx[1904]:     ****  Exiting.

**Comment by matthewwall** [comment]
typo - dtstr should be tstr

fixed in v0.10 of weewx-csv
