### ISSUE TITLE
csv Extension Writes too many data log 

### ISSUE THREAD

**Issue by vdirienzo** [weewx/weewx#282]
I have installed csv Extension v0.10. im using **Simulation station**.

It has pass like 2hs and the CSV files weigh 800k.

Is there any change to configure it to only sample (CSV extenrion) every 5 minutes or something like that? is normal to have 2737 data rows in 2 hs? in a month if i made the correct math it will have 1millon rows.

**Source:** https://github.com/weewx/weewx/wiki/csv

**Station Sample:** http://tatobenia.ddns.net

**Data Sample:** http://tatobenia.ddns.net/data/data-2017-10.csv

# dateTime | UV | altimeter | appTemp | barometer | cloudbase | dewpoint | heatindex | humidex | inDewpoint | inHumidity | inTemp | maxSolarRad | outHumidity | outTemp | pressure | radiation | rain | rainRate | usUnits | windDir | windGust | windGustDir | windSpeed | windchill
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1508251045 | 13.864103 | 33.1581338 | 28.4601092 | 31.1 | 3048.7896 | 27.203561 | 32.678583 | 32.678583 | 31.0795338 | 30 | 63 | None | 80 | 32.678583 | 31.1 | 990.293074 | 0 | 0 | 1 | 360 | 6.20E-09 | 360 | 5.16E-09 | 32.678583
1508251047 | 13.864502 | 33.1581338 | 28.4580737 | 31.1 | 3048.77913 | 27.2017896 | 32.6767655 | 32.6767655 | 31.0795337 | 29.9999996 | 63.0000002 | None | 79.9999997 | 32.6767655 | 31.1 | 990.321574 | 0 | 0 | 1 | 359.999998 | 5.58E-08 | 359.999998 | 4.65E-08 | 32.6767655
1508251050 | 13.8650994 | 33.1581337 | 28.4560387 | 31.1 | 3048.76868 | 27.2000187 | 32.6749486 | 32.6749486 | 31.0795334 | 29.999999 | 63.0000005 | None | 79.9999992 | 32.6749486 | 31.1 | 990.364245 | 0 | 0 | 1 | 359.999995 | 1.55E-07 | 359.999995 | 1.29E-07 | 32.6749486
1508251052 | 13.865497 | 33.1581337 | 28.4540044 | 31.0999999 | 3048.75825 | 27.1982482 | 32.6731323 | 32.6731323 | 31.0795331 | 29.999998 | 63.000001 | None | 79.9999985 | 32.6731323 | 31.0999999 | 990.39264 | 0 | 0 | 1 | 359.999991 | 3.04E-07 | 359.999991 | 2.53E-07 | 32.6731323
1508251055 | 13.8660922 | 33.1581337 | 28.4519708 | 31.0999999 | 3048.74785 | 27.1964782 | 32.6713165 | 32.6713165 | 31.0795325 | 29.9999967 | 63.0000017 | None | 79.9999975 | 32.6713165 | 31.0999999 | 990.435156 | 0 | 0 | 1 | 359.999985 | 5.02E-07 | 359.999985 | 4.18E-07 | 32.6713165
1508251057 | 13.8664883 | 33.1581336 | 28.4499377 | 31.0999999 | 3048.73746 | 27.1947088 | 32.6695013 | 32.6695013 | 31.0795319 | 29.999995 | 63.0000025 | None | 79.9999963 | 32.6695013 | 31.0999999 | 990.463447 | 0 | 0 | 1 | 359.999978 | 7.50E-07 | 359.999978 | 6.25E-07 | 32.6695013

**Comment by matthewwall** [comment]
this is for bug reports.  please direct questions about how to use weewx or weewx extensions to the weewx user group:

http://groups.google.com/group/weewx-user

the answer to your question is in the documentation for the weewx-csv extension:

https://github.com/weewx/weewx/wiki/csv

use 'binding=archive', and possibly append_datestamp and datestamp_format
