### ISSUE TITLE
--reading failure in weewx_3.8.0-1 and weewx-owfs-0.21 Raspberry Pi & DS18B20

### ISSUE THREAD

**Issue by mixpc** [weewx/weewx#289]
Hello,

I have read [issue 77](https://github.com/weewx/weewx/issues/77) and has helped but --readings do not seem to show...

My setup is:

Raspberry Pi 1 Model B running Raspbian Minimal (Stretch)
2017-09-07-raspbian-stretch-lite.img

One-Wire enabled from raspi-configTemperature

Temperature sensor DS18B20 (outdoor-friendly) is pinned to Raspberry GPIO and running python thermometer.py script outputs correct temperature readings.

```
pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.66+ #1059 Fri Dec 1 15:15:38 GMT 2017 armv6l GNU/Linux

```
I have installed Weewx from a .deb as follows:

```
sudo dpkg -i weewx_3.8.0-1_all.deb
sudo apt-get update
sudo apt­-get -f install
sudo apt-get install lighttpd
```
open http://192.168.1.2/weewx/ in web browser and it shows default server
Configured as Simulator because the other options are branded weather stations that do not match my simple temperature sensor setup.

```
wget http://lancet.mit.edu/mwall/projects/weather/releases/weewx-owfs-0.21.tgz
sudo apt-get install python-ow
wee_extension --install weewx-owfs-0.21.tgz
sudo wee_extension --install weewx-owfs-0.21.tgz
```
(without sudo would not work)

To install OWFS as a service...
```
sudo apt-get install python-ow
sudo apt-get install owfs
wee_extension --install weewx-owfs-0.21.tgz
```

To find out sensors I tried with no success:

`sudo PYTHONPATH=/home/weewx/bin python /home/weewx/bin/user/owfs.py --sensors`

But in Issue 77 you wrote about using -iface localhost:4304 and it works!

```
pi@raspberrypi:~ $ sudo PYTHONPATH=/usr/share/weewx python /usr/share/weewx/user/owfs.py --iface localhost:4304 --sensors
67C6697351FF: /10.67C6697351FF DS18S20
4AEC29CDBAAB: /05.4AEC29CDBAAB DS2405
```

Two things here, my sensor is DS18B20 but three-pin layout is the same, though. No idea about DS2405 but it seems it is a 1-wire network branch controller. See... [DS2405 at owfs.org](http://owfs.org/index.php?page=ds2405)

And, as in that Issue, when trying to do the readings this is the output:

```
pi@raspberrypi:~ $ sudo PYTHONPATH=/usr/share/weewx python /usr/share/weewx/user/owfs.py --iface localhost:4304 --readings
67C6697351FF
_usePath: /10.67C6697351FF
_type: DS18S20
_path: /10.67C6697351FF
_useCache: True
  /10.67C6697351FF/scratchpad: ▒▒▒▒f▒\KQ
  /10.67C6697351FF/power: 1
  /10.67C6697351FF/family: 10
  /10.67C6697351FF/locator: ttzxlqrnldwfriez
  /10.67C6697351FF/type: DS18S20
  /10.67C6697351FF/crc8: 8D
  /10.67C6697351FF/temphigh: 24.2793
  /10.67C6697351FF/templow: 7.71973
  /10.67C6697351FF/latesttemp: 4.78051
  /10.67C6697351FF/r_id: FF517369C667
  /10.67C6697351FF/address: 1067C6697351FF8D
  /10.67C6697351FF/errata/: die,trim,trimblanket,trimvalid
  /10.67C6697351FF/r_address: 8DFF517369C66710
  /10.67C6697351FF/r_locator: lqyfpwbewksoflnc
  /10.67C6697351FF/id: 67C6697351FF
  /10.67C6697351FF/temperature: 50.105
4AEC29CDBAAB
_usePath: /05.4AEC29CDBAAB
_type: DS2405
_path: /05.4AEC29CDBAAB
_useCache: True
  /05.4AEC29CDBAAB/type: DS2405
  /05.4AEC29CDBAAB/family: 05
  /05.4AEC29CDBAAB/PIO: 1
  /05.4AEC29CDBAAB/r_locator: vlqbixssctrotcgt
  /05.4AEC29CDBAAB/crc8: 42
  /05.4AEC29CDBAAB/sensed: 0
  /05.4AEC29CDBAAB/r_id: ABBACD29EC4A
  /05.4AEC29CDBAAB/address: 054AEC29CDBAAB42
  /05.4AEC29CDBAAB/r_address: 42ABBACD29EC4A05
  /05.4AEC29CDBAAB/locator: xplcmywcfhrkhwft
  /05.4AEC29CDBAAB/id: 4AEC29CDBAAB

```

I appreciate suggestions to get that --reading value correctly.

Thank you and regards,

**Comment by tkeffer** [comment]
I'm sorry, but this issue list is for tracking known bugs and features. Yours is a support question. You will get much better service posting to the [weewx-user group](https://groups.google.com/forum/#!forum/weewx-user).
