### ISSUE TITLE
Fail with Davis

### ISSUE THREAD

**Issue by MrMerlino** [weewx/weewx#297]
Hello,
i have a Davis Vantage 2 PRO (cabled).
I have this error and can't fix without reboot the system (and it's a problem for me):
Jan  7 17:32:47 serverk systemd[1]: Starting LSB: weewx weather system...
Jan  7 17:32:47 serverk weewx[445]:  * Starting weewx weather system weewx
Jan  7 17:32:47 serverk weewx[457]: engine: Initializing weewx version 3.8.0
Jan  7 17:32:47 serverk weewx[457]: engine: Using Python 2.7.12 (default, Nov 20 2017, 18:23:56) #012[GCC 5.4.0 20160609]
Jan  7 17:32:47 serverk weewx[457]: engine: Platform Linux-4.10.0-42-generic-x86_64-with-Ubuntu-16.04-xenial
Jan  7 17:32:47 serverk weewx[457]: engine: Locale is 'it_IT.UTF-8'
Jan  7 17:32:47 serverk weewx[457]: engine: pid file is /var/run/weewx.pid
Jan  7 17:32:47 serverk weewx[461]: engine: Using configuration file /etc/weewx/weewx.conf
Jan  7 17:32:47 serverk weewx[461]: engine: Loading station type Vantage (weewx.drivers.vantage)
Jan  7 17:32:47 serverk weewx[461]: import of driver failed: [Errno 5] Errore di input/output (<type 'exceptions.IOError'>)
Jan  7 17:32:47 serverk weewx[461]: engine: Unable to load driver: [Errno 5] Errore di input/output
Jan  7 17:32:47 serverk weewx[445]:    ...done.
Jan  7 17:32:47 serverk systemd[1]: Started LSB: weewx weather system.
Jan  7 17:32:47 serverk weewx[461]:     ****  Exiting...

**Comment by tkeffer** [comment]
Please post your question to [weewx-user](https://groups.google.com/forum/#!forum/weewx-user). This list is for bug reporting and tracking. 

Also use `debug=1`. See [Help! Posting to weewx-user](https://github.com/weewx/weewx/wiki/Help!-Posting-to-weewx-user).
