### ISSUE TITLE
Wiki - WeatherCloud - Broken link

### ISSUE THREAD

**Issue by USAFPride** [weewx/weewx#310]
The lancet.mit.edu link no longer works:
https://github.com/weewx/weewx/wiki/weathercloud
http://lancet.mit.edu/mwall/projects/weather/releases/weewx-wcloud-0.11.tgz

**Comment by communitysteps** [comment]
The hosting server at lancet.mit.edu was dropping connections, but now appears to have returned to service. The link is working again.

> Connecting to lancet.mit.edu (lancet.mit.edu)|18.80.0.159|:80... connected.
> HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
> Giving up.

**Comment by tkeffer** [comment]
It does that.
