### ISSUE TITLE
Bad tweet when no connection with weather station

### ISSUE THREAD

**Issue by cryptax** [weewx/weewx#314]
Hi,
In the case there is a connection error with the weather station, the twitter extension tweets a buggy message (see below).

`07:10 Temp: {outTemp:%.1f} °C; Humidité: {outHumidity:%.0f}%; Pression: - hPa; Pluie 1h: 0.000 mm; Vent: 6.7 km/h; Dir: 038`

It would be nice to detect that there are no values and have the choice not to tweet at all. Or tweet something like "connection error" instead of this.

I use weewx 3.8.0 and twitter extension 0.12 on a RPi2 and with WMR200. Thanks!

**Comment by tkeffer** [comment]
Thanks for the report.

The twitter extension is not a supported part of weeWX, but I'm sure we can figure something out.
