### ISSUE TITLE
failures in archive_interval result in no retries

### ISSUE THREAD

**Issue by matthewwall** [weewx/weewx#33]
this has happened on ws23xx and fo hardware.  it happens regularly with ws23xx when there is a lot of RF interference (even with shielded cables and ferrite cores in place).  it could happen to any hardware with a logger.

the StdArchive service tries to get the archive interval from the hardware using the archive_interval property.  when archive_interval fails while querying the hardware, weewx dies.

so far the workaround is to disable any logging capability - both catchup and record_generation=hardware.

desired behavior would be for the engine to reload the driver and start over (as it does when other hardware communication failures happen)

**Comment by tkeffer** [comment]
The engine cannot possibly know all the different kinds of hardware exceptions that could be raised. Instead, it catches a generic `WeeWxIOError` exception. 

It's up to the driver to convert whatever hardware error that occurs into an `WeeWxIOError` exception. Do you know what exception (or error code) is happening in the ws23xx and fo drivers?

**Comment by matthewwall** [comment]
i changed the ws23xx driver so that every known/expected failure will come through as an exception derived from weewx.WeeWxIOError.  will test this for awhile to see if that solves the problem.

**Comment by tkeffer** [comment]
Make sure you push your changes --- I'm not seeing them on GitHub.

**Comment by matthewwall** [comment]
committed at 41fdba1
