### ISSUE TITLE
csv extension configuration

### ISSUE THREAD

**Issue by AJVantage** [weewx/weewx#332]
Hi, 

Is there any option in the Weewx configuration files to control the output variables in the csv extension service file?
* I get the .csv data every two seconds for variables I am not interested in, for example, battery voltage.

Best wishes

AJ

**Comment by tkeffer** [comment]
This kind of general support question is best asked on [weewx-user](https://groups.google.com/forum/#!forum/weewx-user).

This issue list is intended for bug tracking and reporting.
