### ISSUE TITLE
add Evapotranspiration (ET) ( Potential evaporation (PE)) measurements in Vantage driver and in Weewx graphs reports 

### ISSUE THREAD

**Issue by yannick56** [weewx/weewx#348]
Hello,

With the climate change (https://en.wikipedia.org/wiki/Climate_change) ,
can you add EvapoTranspiration (ET) measurement in Vantage driver and display it in Weewx graphs reports like temperature ?
This feature will help farmers to adapt their crops to the climate change.

About EvapoTranspiration (ET) : https://en.wikipedia.org/wiki/Potential_evaporation
https://developer.awhere.com/integration/tutorials/intro-to-pet

Vantage Pro and Vantage Pro2 have calculated EvapoTranspiration (ET) on the console (requires solar radiation sensor in the ISS) 

DESCRIPTION OF EVAPOTRANSPIRATION (ET), REFERENCE ET, AND THE CROP COEFFICIENT in Davis Instruments devices, pages 15 to 17
https://www.davisinstruments.com/product_documents/weather/app_notes/AN_28-derived-weather-variables.pdf

Technical data about Evapotranspiration in Davis Instruments devices, page 3
(Resolution and Units, Range, Update Interval, Calculation and Source, Current Display Data, Current Graph Data, Historical Graph Data, etc...)
http://www.davis.com/Assets/MoreInfo/86403-13Specs.pdf

Keyword ET in the
Vantage Pro TM, Vantage Pro2 TM and Vantage Vue TM Serial Communication Reference Manual
https://www.davisinstruments.com/support/weather/download/VantageSerialProtocolDocs_v261.pdf
pages 18, 23, 26, 30, 32, 33, 54, 57, 59
extract from this documentation:

Field, Offset, Size, Explanation
Day ET,  56, 2, This value is sent as the 1000th of an inch.
Month ET, 58, 2, This value is sent as the 100th of an inch.
Year ET, 60, 2, This value is setnt as the 100th of an inch
ET_DAY_ALARM, 93, 1, The ET day alarm is stored in 1 unsigned byte in the resolution of .001 inches.  A value of 255 means no alarm is set.

XV.EEPROM Graph data locations for Vantage Pro
ET_HOUR                      START + 2918            // 24 ||  1
ET_DAY_TOTAL                 START + 2942            // 25 ||  1
ET_MONTH_TOTAL               START + 2967            // 25 ||  2
ET_YEAR_TOTAL                START + 3017            // 25 ||  2

XVI.EEPROM Graph data locations for VP2
ET_HOUR                      START + 2942            // 24 ||  1
ET_DAY_TOTAL                 START + 2966            // 25 ||  1
ET_MONTH_TOTAL               START + 2991            // 25 ||  2
ET_YEAR_TOTAL                START + 3041            // 25 ||  2

XVII.EEPROM Graph data locations for Vue
#define ET_HOUR                      START+ 2964            // 25  |  1
#define ET_DAY_TOTAL                 START + 2989            // 26  |  1
#define ET_MONTH_TOTAL               START + 3015            // 26  |  2
#define ET_YEAR_TOTAL                START + 3067            // 26  |  2

Best regards

**Comment by tkeffer** [comment]
Evapotranspiration has been in the Vantage driver for 8 years as observation type `ET`.
