### ISSUE TITLE
Sending weatherdata on each LOOP packet to url

### ISSUE THREAD

**Issue by vannut** [weewx/weewx#350]
I'm looking for a way to hit an url on the receive of each loop packet.
If I look at the user guide, i can see the [StdRESTful] section and was thinking I need to configure something here.
But I can't see a 'default' extension. Am i missing something? 
Is it possible to built my own extension; heavily based on the rapidfire Wunderground extension, but with my own URL instead of wundergrounds :)

**Comment by tkeffer** [comment]
Hello.

The issues list is intended for development work. Could you please direct your question to the [user's group](https://groups.google.com/forum/#!forum/weewx-user)? This way others will see it and, hopefully, answer it.
