### ISSUE TITLE
lowBattery.py needs option to use SMTP_SSL

### ISSUE THREAD

**Issue by whorfin** [weewx/weewx#351]
For sites such as gmx.com, making an unencrypted communication channel and then negotiating starttls doesn't go so well, as the unecrypted connection is not supported.  In plain terms, the `smtplib.SMTP(self.smtp_host)` call hangs for a while and then fails.  This migration to mandatory SSL for outgoing SMTP has become not uncommon.

Using `smtplib.SMTP_SSL(self.smtp_host)` works fine.

Rather than catching a fail on the first connection, which wastes time, perhaps we could have a flag to indicate SSL or not connections, as is commonly done with mail clients.

**Comment by tkeffer** [comment]
Fixed in commit https://github.com/weewx/weewx/commit/cafce974c924cb637edb9120f9d36e5f056021f8
