### ISSUE TITLE
wiring rpi to davis instruments Vantage Vue Console

### ISSUE THREAD

**Issue by dwc54** [weewx/weewx#376]
to connect this to a Vantage Vue Console could i wire the hardware uart pins of the pi into the Expansion port or how would i connect it?

http://2.bp.blogspot.com/_Nvf6aanA8XE/TTzcIXs-aJI/AAAAAAAAAKQ/SFMqAEJXWZY/s1600/VP2+Expansion.jpg

**Comment by tkeffer** [comment]
Please ask your question on the [weewx-user group](https://groups.google.com/forum/#!forum/weewx-user). This way, others can learn and contribute. This issues list is for bug reporting and tracking.

thanks!
