### ISSUE TITLE
need ability to set mqtt clientid

### ISSUE THREAD

**Issue by landloos** [weewx/weewx#385]
I'm using the Mosquitto (v4) addon in Hassio. 

I'm getting the following problem connecting to my MQTT server:
ACL denying access to client with dangerous client id "paho/xxxxxxxxxxxx"

From my research, this is caused by the "/" in the client id which Mosquitto flags as invalid or dangerous. I need a way to add a manually assigned a clientid to the weewx.conf so I can give it a valid one or somehow remove the "/ " from the auto generated id.

**Comment by tkeffer** [comment]
Hello, this list is for tracking and fixing WeeWX bugs. The MQTT uploader is not a supported part of WeeWX.

Could you please post your query on [weewx-user](https://groups.google.com/forum/#!forum/weewx-user)?
