### ISSUE TITLE
JSON data in Seasons skin 

### ISSUE THREAD

**Issue by cincuranet** [weewx/weewx#387]
Would it be interesting for the project to have a PR with addition of one JSON file with curent conditions (same as the first "widget" in the skin) in it? I'm using it and it's quite useful, because the data can be easily processed on another side.

I know it could be separate skin and I can do such PR as well, but because the Seasons already contains i.e. RSS feed this might make it more complete.

**Comment by tkeffer** [comment]
Thank you for your proposal. Both it and RSS really have nothing to do with the rest of Seasons. They would not be used by Seasons and both should most properly be separate skins.

NB: Issue #341 directly addresses allowing JSON to be a first-class formatting option. 

So, to answer your question, sure it would be of interest, but I think it's more complicated.
