### ISSUE TITLE
Precipitation not appearing in downloaded JSON String

### ISSUE THREAD

**Issue by bill-orange** [weewx/weewx#391]
I have successfully registered my PWS, uploaded data to it using Weewx with the OpenWeatherMap patch.

I can retrieve my data okay and all is well except for precipitation. 

Rainfall is showing up in Weewx but does not show up in my downloaded JSON string. This is all I get ("precipitation": {}). Everything else works.

Is precipitation data working in OpenWeatherMap for PWS? I suspect that it is not since everything on my end seems to check out.  

The remaining possibility is that Weewx is not uploading rainfall.  Is that possible.

Thanks,

Bill

**Comment by tkeffer** [comment]
Bill, this list is for WeeWX bug reporting and tracking. OpenWeatherMap is not part of WeeWx. You'll have better luck asking your question on the [weewx-user](https://groups.google.com/forum/#!forum/weewx-user) list.
