### ISSUE TITLE
UKMO forecast not displayingcorrectly

### ISSUE THREAD

**Issue by 1234phil** [weewx/weewx#395]
My forecast comes from the UK Met Office and I don't seem to get the full forecast.

If you view http://sheringhamweather.ddns.net/forecast/single-stripQnap.html I just get a days short summary with no forecast and looking in the forecast.sdb I view what I receive

But if I go to 
http://datapoint.metoffice.gov.uk/public/data/val/wxfcs/all/xml/354731?res=3hourly&key=8f916e8d-7477-4198-8ecc-ae764ff7bb84
It shows me what I should get.
Anybody help me to where Im going wrong please
Sorry if this is in the wrong place
Thanks Phil

**Comment by tkeffer** [comment]
This issues list is for bug reporting and tracking. You'll have better luck at the [weewx-user group](https://groups.google.com/forum/#!forum/weewx-user).
