### ISSUE TITLE
Document setup.cfg better (SF: #28)

### ISSUE THREAD

**Issue by alco28** [weewx/weewx#4]
Nowhere in the docs does it describe the role of setup.cfg.

[Note: pulled from sourceforge issue 28]( https://sourceforge.net/p/weewx/tickets/28/ )

**Comment by matthewwall** [comment]
i suggest we punt this issue.

for the sake of 'wee-ness', we could probably punt 'home' and just use 'prefix', but in practice it does not matter.

i have tried to override home and prefix, but no joy:

setup.py install --home=/opt/weewx

according to the documentation, one must specify either home or prefix, but not both.  i have tried removing home from setup.cfg, with prefix=/home/weewx in setup.cfg and a commandline override to /opt/weewx.  no joy.

setup.py install --prefix=/opt/weewx

the only reliable approach i have is to use sed or perl to replace the setting for home:

sed -i -e 's%home = .*%home = /opt/weewx%' setup.cfg

compared to command-line, changing setup.cfg has the benefit of documenting where you actually installed weewx.  perhaps we should add setup.cfg to the .gitignore list?

setup.cfg is poorly documented by the python gods:

https://packaging.python.org/en/latest/
https://github.com/pypa

more background info:

http://stackoverflow.com/questions/27077355/how-to-use-setup-cfg-instead-of-setup-py-with-python-2-7
http://stackoverflow.com/questions/30191631/referring-to-existing-distutils-options-inside-setup-cfg-and-setup-py
