### ISSUE TITLE
Weather Underground new forecast URL format

### ISSUE THREAD

**Issue by SylvainGa** [weewx/weewx#401]
Weather Underground changed their forecast URL format. Old format:

http://api.wunderground.com/api/{ApiKey}/hourly5day/q/{GeoLocation}.json doesn't work any more. I  get a "keynotfound" error. Confirmed by Weather Underground tech support:

You’re using the key in the wrong commands. You cannot use the new key in old commands. The commands the key you generated will work with are listed here: https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY

The following URL works

http://api.weather.com/v3/wx/forecast/daily/5day?format=json&units=e&language=en-US&geocode={GeoLocation}&apiKey={apiKey}

For me, 5day works but 3day, 10day and 15day gives me an access denied. I only pay for the $10 a year subscription.

This is the output I get:

{"dayOfWeek":["Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],"expirationTimeUtc":[1556066645,1556066645,1556066645,1556066645,1556066645,1556066645],"moonPhase":["Waning Gibbous","Waning Gibbous","Waning Gibbous","Last Quarter","Waning Crescent","Waning Crescent"],"moonPhaseCode":["WNG","WNG","WNG","LQ","WNC","WNC"],"moonPhaseDay":[19,20,21,22,23,23],"moonriseTimeLocal":["","2019-04-24T00:45:18-0400","2019-04-25T01:38:16-0400","2019-04-26T02:22:46-0400","2019-04-27T03:01:06-0400","2019-04-28T03:33:49-0400"],"moonriseTimeUtc":[null,1556081118,1556170696,1556259766,1556348466,1556436829],"moonsetTimeLocal":["2019-04-23T09:01:39-0400","2019-04-24T09:48:54-0400","2019-04-25T10:40:43-0400","2019-04-26T11:37:19-0400","2019-04-27T12:35:42-0400","2019-04-28T13:36:26-0400"],"moonsetTimeUtc":[1556024499,1556113734,1556203243,1556293039,1556382942,1556472986],"narrative":["Cloudy, periods of rain. Lows overnight in the low 40s.","Mostly cloudy. Highs in the low 50s and lows in the mid 30s.","Partly cloudy. Highs in the low 60s and lows in the low 40s.","Showers possible. Highs in the mid 50s and lows in the upper 30s.","Clouds giving way to sun . Highs in the low 40s and lows in the low 30s.","Mix of rain and snow showers. Highs in the low 40s and lows in the low 30s."],"qpf":[0.2,0.0,0.02,0.18,0.0,0.26],"qpfSnow":[0.0,0.0,0.0,0.0,0.0,0.0],"sunriseTimeLocal":["2019-04-23T06:03:43-0400","2019-04-24T06:02:06-0400","2019-04-25T06:00:30-0400","2019-04-26T05:58:55-0400","2019-04-27T05:57:21-0400","2019-04-28T05:55:47-0400"],"sunriseTimeUtc":[1556013823,1556100126,1556186430,1556272735,1556359041,1556445347],"sunsetTimeLocal":["2019-04-23T19:58:55-0400","2019-04-24T20:00:11-0400","2019-04-25T20:01:26-0400","2019-04-26T20:02:42-0400","2019-04-27T20:03:57-0400","2019-04-28T20:05:13-0400"],"sunsetTimeUtc":[1556063935,1556150411,1556236886,1556323362,1556409837,1556496313],"temperatureMax":[null,50,60,56,43,43],"temperatureMin":[41,36,40,38,31,31],"validTimeLocal":["2019-04-23T07:00:00-0400","2019-04-24T07:00:00-0400","2019-04-25T07:00:00-0400","2019-04-26T07:00:00-0400","2019-04-27T07:00:00-0400","2019-04-28T07:00:00-0400"],"validTimeUtc":[1556017200,1556103600,1556190000,1556276400,1556362800,1556449200],"daypart":[{"cloudCover":[null,99,90,49,41,71,97,89,63,57,82,65],"dayOrNight":[null,"N","D","N","D","N","D","N","D","N","D","N"],"daypartName":[null,"Tonight","Tomorrow","Tomorrow night","Thursday","Thursday night","Friday","Friday night","Saturday","Saturday night","Sunday","Sunday night"],"iconCode":[null,12,26,29,30,45,11,45,30,27,5,45],"iconCodeExtend":[null,1200,2600,2900,3000,7100,1100,6100,9003,2700,4900,6100],"narrative":[null,"A steady rain this evening. Showers continuing overnight. Low 41F. SE winds shifting to WSW at 10 to 20 mph. Chance of rain 100%. Rainfall around a quarter of an inch.","Cloudy. High around 50F. Winds WNW at 10 to 20 mph.","A few clouds from time to time. Low 36F. Winds NNW at 5 to 10 mph.","Intervals of clouds and sunshine. High around 60F. Winds SSW at 5 to 10 mph.","Partly cloudy skies early followed by increasing clouds with showers developing later at night. Low around 40F. Winds E at 5 to 10 mph. Chance of rain 40%.","Considerable cloudiness with occasional rain showers. High 56F. Winds NE at 5 to 10 mph. Chance of rain 50%.","Showers in the evening, then cloudy overnight. Low 38F. Winds WNW at 10 to 15 mph. Chance of rain 40%.","Cloudy skies early, then partly cloudy in the afternoon. High 43F. Winds WNW at 15 to 25 mph.","Partly cloudy skies in the evening, then becoming cloudy overnight. Low 31F. Winds NW at 10 to 15 mph.","Rain and snow showers in the morning changing to rain showers in the afternoon. High 43F. Winds N at 10 to 15 mph. Chance of rain 40%.","Rain showers early with overcast skies late. Low 31F. Winds NW at 10 to 15 mph. Chance of rain 40%."],"precipChance":[null,100,20,10,10,40,50,40,20,10,40,40],"precipType":[null,"rain","rain","precip","rain","rain","rain","rain","rain","precip","rain","rain"],"qpf":[null,0.22,0.0,0.0,0.0,0.02,0.15,0.03,0.0,0.0,0.2,0.06],"qpfSnow":[null,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],"qualifierCode":[null,null,null,null,null,null,null,null,null,null,null,null],"qualifierPhrase":[null,null,null,null,null,null,null,null,null,null,null,null],"relativeHumidity":[null,90,71,73,57,73,73,84,58,61,55,66],"snowRange":[null,"","","","","","","","","","",""],"temperature":[null,41,50,36,60,40,56,38,43,31,43,31],"temperatureHeatIndex":[null,51,49,47,59,56,54,51,43,42,43,42],"temperatureWindChill":[null,35,35,37,39,39,39,32,31,27,26,24],"thunderCategory":[null,"No thunder","No thunder","No thunder","No thunder","No thunder","No thunder","No thunder","No thunder","No thunder","No thunder","No thunder"],"thunderIndex":[null,0,0,0,0,0,0,0,0,0,0,0],"uvDescription":[null,"Low","Moderate","Low","High","Low","Moderate","Low","High","Low","Moderate","Low"],"uvIndex":[null,0,4,0,6,0,3,0,6,0,3,0],"windDirection":[null,230,303,338,209,89,56,284,296,316,353,320],"windDirectionCardinal":[null,"SW","WNW","NNW","SSW","E","NE","WNW","WNW","NW","N","NW"],"windPhrase":[null,"SE winds shifting to WSW at 10 to 20 mph.","Winds WNW at 10 to 20 mph.","Winds NNW at 5 to 10 mph.","Winds SSW at 5 to 10 mph.","Winds E at 5 to 10 mph.","Winds NE at 5 to 10 mph.","Winds WNW at 10 to 15 mph.","Winds WNW at 15 to 25 mph.","Winds NW at 10 to 15 mph.","Winds N at 10 to 15 mph.","Winds NW at 10 to 15 mph."],"windSpeed":[null,14,14,8,7,7,8,12,17,12,10,10],"wxPhraseLong":[null,"Rain","Cloudy","Partly Cloudy","Partly Cloudy","Showers Late","Showers","Showers Early","AM Clouds/PM Sun","Mostly Cloudy","Rain/Snow Showers","Showers Early"],"wxPhraseShort":[null,"Rain","Cloudy","P Cloudy","P Cloudy","Shwrs Late","Showers","Shwrs Early","AM Clouds","M Cloudy","R/S Showers","Shwrs Early"]}]}

**Comment by tkeffer** [comment]
Please note that the WU forecast API is not used by WeeWX.

Closing this issue.
