### ISSUE TITLE
option for Log to stdout 

### ISSUE THREAD

**Issue by phinnay** [weewx/weewx#421]
I am running WeeWX inside Docker and it's tricky to troubleshoot as all logging is dumped to syslog. I'm working around it by running a syslog daemon inside the container but this goes against best practice. 

Would it be possible to add a flag to dump all output to stdout/stderr?

**Comment by tkeffer** [comment]
Yes, of course it's possible. As always, PRs are welcome.

**Comment by kadaan** [comment]
@phinnay @tkeffer I've created PR #721 to address this issue.
