### ISSUE TITLE
Directpost (WSWIN)

### ISSUE THREAD

**Issue by tho-wa** [weewx/weewx#423]
Is it possible to extend the weather site function to support DirectPost format? (WsWin)

**Comment by tkeffer** [comment]
Don't know what DirectPost is, nor WsWin

**Comment by matthewwall** [comment]
it looks like another regional weather data aggregator:

https://www.meteopool.org/de/

their api is not obviously available...

**Comment by tkeffer** [comment]
Agreed. A good candidate for a 3rd party uploader. It would have to demonstrate considerable traction before it became part of the core WeeWX
