### ISSUE TITLE
How to add a new aggregation service

### ISSUE THREAD

**Issue by fizzi** [weewx/weewx#424]
Hi all,

I'd like to add a new aggregation service.

Is there any documentation on how to add a new aggregation service? Otherwise where can I see an example on how to do it?

I would like to store the data on elasticsearch

**Comment by matthewwall** [comment]
the customization guide contains the formal documentation for extending weewx

however, the best way to learn how to make an uploader is to look at one of the existing uploaders.  there are a few included with weewx (look in restx.py).  but even easier is to look at one of the uploader extensions on the weewx wiki.  there are 24 of them listed there.  some upload only a limited number of fields, others are much more general.  most use http(s), but there is also mqtt.

if you have questions, please post to the weewx-development group at google groups.
