### ISSUE TITLE
realtime.txt contains NULL when Wundeground gets the right dada

### ISSUE THREAD

**Issue by goldriver2** [weewx/weewx#427]
I have installed the weemx crt addon few days ago, I can see that data sent to realtime.txt often have Null data  while data sent to wunderground seems to be the right information 

i have attached two reatime.txt file to show the content, any idea what could be wrong ?

27/06/19 05:40:05 NULL NULL NULL 0.0 NULL NULL 0.0 0.0 NULL --- NULL km/h C mb mm 0.0 NULL 48.8 48.8 3.0 25.9 NULL NULL NULL 16.3 00:05 13.0 05:10 0.3 05:25 2.7 05:25 1018.3 05:35 1016.2 00:30 3.9.1 0 0.0 NULL NULL NULL NULL NULL NULL 0.0 0 1 0 --- NULL m NULL 0.5 NULL 0

27/06/19 05:47:35 13.0 99 12.8 0.0 0.0 NULL 0.0 0.0 NULL --- 0 km/h C mb mm 0.0 NULL 48.8 48.8 3.0 NULL NULL 13.0 -1.3 16.3 00:05 13.0 05:40 0.3 05:25 2.7 05:25 1018.4 05:40 1016.2 00:30 3.9.1 0 0.0 13.0 15.7 NULL NULL NULL NULL 0.0 0 1 0 --- 192 m 13.9 0.7 NULL 0

I am using an Acurite 1036 connected to weemx on a Pi.

**Comment by tkeffer** [comment]
This issues list is for bug tracking. You'll have to ask your question on [weewx-user](https://groups.google.com/forum/#!forum/weewx-user).
