### ISSUE TITLE
wunderground again (sigh)

### ISSUE THREAD

**Issue by RPeters52** [weewx/weewx#433]
I just updated to weewx 3.9.2 from 3.9.1 and **everything** seems to be working fine EXCEPT wunderfixer...which worked the last time I tried it several weeks (months?) ago.  I get:

wunderfixer -e 250 -t
Using configuration file /etc/weewx/weewx.conf.
Using database binding 'wx_binding', which is bound to database 'archive_sqlite'
Unable to open Weather Underground station KNMALBUQ335  or  HTTP Error 403: Forbidden
Could not get Weather Underground data. Exiting.

Since I am connecting to wunderground (see https://www.wunderground.com/dashboard/pws/KNMALBUQ335), I am not sure what the problem is -- possibly the new wunderground owners have made "changes".  Does anyone have any ideas??  Or the same problem?  **Thanks**!!

BTW, I am using my previous weewx.conf as I had a number of modifications in it for "stale data", calibrating temps...

**Comment by gjr80** [comment]
Suggest you have a search of the forums for ‘wunderfixer’ over the past few months. I believe Leon may have done some work and created a workaround; however, I don’t believe any of that work has yet been committed here (and hence the yet to be released next version of WeeWX you have does not include the workaround).

**Comment by RPeters52** [comment]
Thanks!  I will check it out.

**Comment by RPeters52** [comment]
So, I downloaded the development branch wunderfixer and tried it
File last mod:
1.4.1 05/14/2019
Made WunderStation class consistent with restx.AmbientThread parameters


and I ran it to get:
wunderfixer -e250 -t
Using configuration file /etc/weewx/weewx.conf.
Using database binding 'wx_binding', which is bound to database 'archive_sqlite'
Traceback (most recent call last):
  File "/usr/bin/wunderfixer", line 512, in <module>
    main()
  File "/usr/bin/wunderfixer", line 223, in main
    softwaretype = "wunderfixer-%s" % __version__)
TypeError: __init__() got an unexpected keyword argument 'q'


The section that fails is:

    # Get a WunderStation object so we can interact with Weather Underground
    wunder = WunderStation(q=None,  # Bogus queue. We will not be using it.
                           manager_dict=dbmanager_t,
                           station=options.station,
                           password=options.password,
                           server_url=weewx.restx.StdWunderground.pws_url,
                           protocol_name = "wunderfixer",
                           essentials=_essentials_dict,
                           softwaretype = "wunderfixer-%s" % __version__)


Oh well....

**Comment by gjr80** [comment]
I think you will find that none of the workarounds that make wunderfixer work with the ‘new’ WU API have been committed to the WeeWX github repo. The issue you have struck with the development branch may have to do with 3.9.2 incompatibility with the development branch version of wunderfixer, it doesn’t look like a problem with WU per se. That is one of the dangers you run into using development. You may get better mileage asking in [this thread](https://groups.google.com/forum/m/#!topic/weewx-user/dq8xFrqGVMA/discussion).

**Comment by RPeters52** [comment]
Thanks for the response!!  I guess that I can wait until someone figures out this mess...  

One of the rules that I had when writing software is that "interfaces" change only if absolutely necessary.  One can add new/modified interfaces but one should try to keep the old ones viable...  Otherwise chaos....
