### ISSUE TITLE
Transfer from sqlite to MySQL sed is incomplete

### ISSUE THREAD

**Issue by eardkdw** [weewx/weewx#437]
The sed command starting `sed -e '/PRAGMA/d'` needs one extra term as you get a Error 1064 when you try the import. This is because one of the fields is called `interval`; `INTERVAL` is a MySQL keyword. It needs escaping.

    sed -e '/PRAGMA/d' -e's/BEGIN/START/' -e 's/"archive"/archive/' -e 's/interval/`&`/' < weewx.sql |  mysql -u weewx -p weewx

 works.

**Comment by tkeffer** [comment]
Feel free to amend the Wiki.
