### ISSUE TITLE
web server directory

### ISSUE THREAD

**Issue by jmentero** [weewx/weewx#439]
I have raised this question in the weewx google groups but no luck so far. 
Files are being uploaded to a directory /www/exfoliation instead of /www/ (public_html directory 
on the web host server). Path is specified as /www in weewx.conf

A server redirection using .htaccess creates other issues.

Any way to have the files ftp'd to the /www directory ?

Weewx is 3.9.2 installed using apt-get, exfoliation 0.45 installed as per github instructions in WS2080.
Miguel

**Comment by gjr80** [comment]
Refer https://groups.google.com/d/topic/weewx-user/OmuJWCkYF34/discussion
