### ISSUE TITLE
Explicit USB device for docker

### ISSUE THREAD

**Issue by bordershot** [weewx/weewx#447]
I'm trying to setup weewx in docker and I'd like to directly pass the device rather than have the acurite driver scan the usb bus--I'm trying to follow this pattern:

udev rule:
```# /etc/udev/rules.d/weewx.rules
SUBSYSTEM!="usb_device", ACTION!="add", GOTO="weewx_rules_end"

# acurite usb 24c0:0003
SYSFS{idVendor}=="24c0", SYSFS{idProduct}=="0003", GROUP="users", MODE="0666", SYMLINK+="usb/weather"

LABEL="weewx_rules_end"
```

And then call docker with "--device /dev/usb/weather:/dev/usb/weather" to pass through my symlink'd device. I'd like to then pass '/dev/usb/weather' to weewx, but I don't see that the acurite driver allows a device to be specified?

**Comment by tkeffer** [comment]
Hello,

This list is for tracking bugs and feature development. Direct your question to the User's Group, [weewx-user](https://groups.google.com/forum/#!forum/weewx-user).
