### ISSUE TITLE
mqtt aggregation - option for non-string values

### ISSUE THREAD

**Issue by erudita** [weewx/weewx#448]
mqtt-0.19 works well (thanks Matthew).
However, there are circumstances where it would be advantageous to have the "weather/loop" json use "float" type for the values rather than strings, e.g. `"UV": 6.5` instead of `"UV": "6.5"`
These circumstances include integration of "weather/loop" into telegraf.

I have added said functionality as a backwards-compatible, configurable item which publishes aggregate mqtt (weather/loop) values as float (except dateTime which is an integer).
This enables quick integration into telegraf and the ability to preserve the same datetime.

I am happy to share via Pull Request. Please let me know if this is a good way forward.

**Comment by tkeffer** [comment]
The MQTT driver is not part of WeeWX, so a PR would not help. You'll have to negotiate directly with Matthew.
