### ISSUE TITLE
3.2.0a4: inconsistent use of double quotes for station location

### ISSUE THREAD

**Issue by matthewwall** [weewx/weewx#45]
1) clean install with location name 'whatever'
  2) wee_config --reconfigure
  3) location name no longer has double quotes around it

there is logic in the code for dealing with a location that has a comma in it, so there is no need to put the location in double quotes.

**Comment by tkeffer** [comment]
I'm not sure there is much we can do about this. ConfigObj immediately converts any value, quoted or not, into a string, stripping off the quotes. Try this:

```python
import StringIO
import configobj

s = StringIO.StringIO('''[Station]
qlocation = "A quoted string"
slocation = An unquoted string
''')

c = configobj.ConfigObj(s)
print c
```

The results will be:
```
{'Station': {'qlocation': 'A quoted string', 'slocation': 'An unquoted string'}}
```

The good news is that, semantically, there is no difference whether the location is enclosed in quotes or not.

**Comment by matthewwall** [comment]
thanks for the explanation.  the issue is not very important - it came up as i was diff-ing weewx.conf from before and after changes made by wee_config.
