### ISSUE TITLE
Please add --date option to wee_database transfer

### ISSUE THREAD

**Issue by Seb-Sch** [weewx/weewx#451]
I want to migrate from sqlite to mysql. However, I have 1,7 millions of records in the archive.

The problem using `transfer ` is that it **always** starts from the very beginning. If, however, the transfer process is interupted (for me: now the third time after more than 8 hours), you have to start from the beginning again and have no possibility to continue the transfer process.

Would it be possible to add a `--date` parameter (as for `rebuild_daily`) to the transfer process? This would enable a kind of "bulk transfer".

Thank you in advance!

**Comment by tkeffer** [comment]
Looked at this. It's not super hard to do, but, realistically, it's just not a priority. It only affects users with large databases, who are doing a transfer, which gets interrupted. I don't think there are many people in this situation. There is an alternative, albeit a slow one.

Of course, a PR is always welcome!
