### ISSUE TITLE
3.2.0a4: dangling commas in service lists

### ISSUE THREAD

**Issue by matthewwall** [weewx/weewx#46]
1) clean install
2) check weewx.conf: no comma at end of archive_services
3) wee_extension --install forecast.tgz
4) wee_extension --uninstall forecast
5) archive_services now has a dangling comma

also, data_services starts out with a dangling comma.  the code should be smart enough to deal with dangling commas, but we should not put them in weewx.conf in the first place and whatever wee_* utilities process weewx.conf should not leave them.

**Comment by tkeffer** [comment]
A dangling comma is actually ConfigObj's way of signalling that the contents are a list. To work around this, we developed utility weeutil.weeutil.option_as_list()
