### ISSUE TITLE
Installation Prerequisites update

### ISSUE THREAD

**Issue by harmlessdrudge** [weewx/weewx#462]
http://www.weewx.com/docs/setup.htm

lists 

# required if using MySQL:
sudo apt-get install mysql-client

This elicits a message that mysql-client module is not available and has been replaced by mariadb-client-10.0

It _may_ be worth noting that temporary ramdisk storage should not be used when installing pyphem (I copied an old fstab when reinstalling and found that the installation ran out of space--w 5Mb);

**Comment by tkeffer** [comment]
1. I'm hesitant to clutter up simple install instructions with possible warnings.
2. Same issue. The right place to put this is in the Wiki, possibly the article on [minimizing writes](https://github.com/weewx/weewx/wiki/Minimize-writes-on-SD-cards).
