### ISSUE TITLE
Add PostgreSQL database

### ISSUE THREAD

**Issue by Hofei90** [weewx/weewx#466]
Please add support for PostgreSQL database.
https://www.postgresql.org/

For the easier handling of the different databases a database ORM would be suitable in Python.
Privately I use Peewee:
http://docs.peewee-orm.com/en/latest/index.html

Of course, there are other alternatives.

Many thanks in advance 
and at this point a big general thank you for the weeWx software. Great work

**Comment by tkeffer** [comment]
Unfortunately, not a priority, and not an easy project. 

PRs are always welcome.

**Comment by tkeffer** [comment]
Clay, have you seen this? 

https://github.com/tkeffer/weewx-postgresql
