### ISSUE TITLE
Adding alternative source for a sensor data

### ISSUE THREAD

**Issue by Jafaral** [weewx/weewx#483]
The humidity sensor has failed in my weather station giving 99% reading all the time. Is there an easy way to disable that sensor in weewx? Or better, is there a way to pull this data from other  nearby stations?

Thanks.

**Comment by tkeffer** [comment]
The issues list is for bug tracking. Please post your question in [weewx-user](https://groups.google.com/forum/#!forum/weewx-user). It will have a better chance of getting answered there.
