### ISSUE TITLE
weatherlink.com wlink driver 2020 invalid account information

### ISSUE THREAD

**Issue by rgusso** [weewx/weewx#492]
Hi, I`m getting: 

Caught WeeWxIOError: cannot determine archive interval from WeatherLink Server Error: Invalid Account Information#012Please ignore any error messages of the type: Invalid Account Information

already tried username and password in quotes and without. no luck!

is this something about the new weatherlink site?

**Comment by tkeffer** [comment]
This list is for bug tracking. You will have better luck getting your question answered on the [weewx-user](https://groups.google.com/forum/#!forum/weewx-user) forum.
