### ISSUE TITLE
MS SQL database connection

### ISSUE THREAD

**Issue by dolenec** [weewx/weewx#493]
Is it possible to add support for MS SQL database?

Currently I'm using on Raspberry Pi3 with mySQL database on QNAP NAS.

Now I will make virtualization of Raspberry Pi3 and weewx and I would like to run database on MS SQL server which is running in docker on NAS.

**Comment by tkeffer** [comment]
It's certainly "possible", but not a priority. If we were to add another database, PostgreSQL would be more likely, as it is an open-source product. Not many people using MS SQL in the open-source world.

But, as always, a pull-request is always welcome. Just be warned, writing a database interface is not a trivial project!
