### ISSUE TITLE
MySQL Error 1927 (Connection was killed) causing Weewx exit

### ISSUE THREAD

**Issue by Dreytac** [weewx/weewx#502]
This may be intended behaviour but I thought I'd report it anyway. I have MariaDB hosted in a Docker on another server. Weewx is running on a RaspberryPi 3 and is set to archive every minute. It works great until the Docker image is updated or restarted.

Whenever the Docker container is restarted the following error (1927) occurs when Weewx next tries to write to the database and Weewx exits. I thought it would behave similar to the (2013) error and just retry after 2 minutes but that's not the case.

In the log file I waited until Weewx started the "main packet loop", then restarted the database. Is there any chance of adding this error as a retry option as well?

To reproduce: 
1. Connect Weewx to a database docker container.
2. Start Weewx.
3. Restart docker container.
4. Wait for Weewx to attempt to write to the database.

Log file: [weewx.txt](https://github.com/weewx/weewx/files/4146598/weewx.txt)

**Comment by tkeffer** [comment]
Thanks for your comments.

This was fixed about a month ago in commit https://github.com/weewx/weewx/commit/d1b15032f743c4f35205a2b273731ae49b318db9, to appear in V4.
