### ISSUE TITLE
Please add support for wind stats

### ISSUE THREAD

**Issue by kacnje** [weewx/weewx#504]
It would be very nice if this skin can show wind gust statistics ... please.

**Comment by tkeffer** [comment]
I don't know what skin you are referring to, but it's  easy enough to add yourself. Something like

    <p>The max wind gust today is $day.windGust.max</p>

See the Customizing Guide.

**Comment by kacnje** [comment]
Oh, sorry, my mistake. I was on xstats website in one tab in the browser and on this page ... 
Is something similar for all time? Like $alltime.windGust.max
I'm a noob, sorry.

**Comment by tkeffer** [comment]
This issues list is for bug reporting and tracking. You would be better off asking your questions on [weewx-user](https://groups.google.com/forum/#!forum/weewx-user). That way, others can answer, and learn from the responses.

**Comment by kacnje** [comment]
Understand. Thank you for your effort. 

Janez
