### ISSUE TITLE
Consider adding distutils to Python3 in docs/setup.htm

### ISSUE THREAD

**Issue by rezin8** [weewx/weewx#506]
I was installing 4.0.0b11 today using the instructions in docs/setup.conf for Python3 in a RPi, and ran into ModuleNotFoundError: No module named 'distutils.core'. Once I installed the module, the setup ran fine. I would recommend adding that as a step in setup.htm to help out any confusion for other users. Added a screenshot for clarity. 

<img width="791" alt="Screen Shot 2020-02-06 at 11 29 56 AM" src="https://user-images.githubusercontent.com/4650025/73957446-600db880-48d4-11ea-9e24-310a0b12736f.png">

**Comment by tkeffer** [comment]
@gjr80 discovered this earlier.

What OS are you using, and can you recall whether you used a regular, or minimal, build?

**Comment by rezin8** [comment]
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

It's Raspbian Lite, which is a minimal build.

**Comment by tkeffer** [comment]
We can conclude this is common enough it's worth including in the instructions.

Commit https://github.com/weewx/weewx/commit/aaa3eb065110a56491b8e4d52848efe9700c927b

Note to @matthewwall: this means we will have to add it to `pkg/debian/control`, no?
