### ISSUE TITLE
Problem with logging in WeeWX4 

### ISSUE THREAD

**Issue by dweimer** [weewx/weewx#507]
I am working on testing weewx 4.0.0b11 on FreeBSD 12.1 with Python 3.7

I had to make the following changes to get it to run without errors.

# diff bin/weeutil/logger.py bin/weeutil/logger.py.orig
26,28d25
< elif sys.platform.startswith('freebsd'):
<     address = '/var/run/log'
<     facility = 'user'

to /etc/syslog.conf:
user.*                                 /var/log/weewx4.log

created the new file and restarted syslogd service:
touch /var/log/weewx4.log
service syslogd restart

and finally created a configuration file to do log rotates.
/usr/local/etc/newsyslog.conf.d/weewx4.conf
# logfilename           [owner:group]   mode    count   size    when    flags   [/pid_file]     [sig_num]
/var/log/weewx4.log     root:wheel      644     7       *       @T00    JC

**Comment by tkeffer** [comment]
I made the changes to `weeutil/logger.py` in commit https://github.com/weewx/weewx/commit/c962e5208609cded0bfacbc6581213c8f27c0c85

The others are more configuration issues. Could you write a Wiki article about them?
