### ISSUE TITLE
dayrain_mm wrong in fousb driver

### ISSUE THREAD

**Issue by rbonvino** [weewx/weewx#513]
Driver for fine offset usb shows a wrong dayrain_mm value in weewx 3.9.2. Could you check? Thanks in advance.

**Comment by tkeffer** [comment]
Don't know what you mean by 'dayrain_mm'. There is no such value in the FO driver. 

And, what do you mean by 'wrong'. We need something more specific.

Closing for now. Please reopen if you can provide specifics.
