### ISSUE TITLE
Rain unit problem

### ISSUE THREAD

**Issue by Drealine** [weewx/weewx#514]
Hi,

Since few days ago, I use a custom driver for WeatherLink Live to archive data from it.
I stuck on a problem. In fact, I don't understand how weewx convert rain unit.

When I calculate directly before weewx put on sql table, I've a wrong value.
So, to work properly, I convert value on inch to have the good value in mm (metrix unit and my rain collector is set to 0.2mm)

I've already test to change the sql table to METRIC but still nothing

Thank for your support

**Comment by tkeffer** [comment]
This issues list is for bug reporting and tracking. You will be better off directing your question to the group [weewx-development](https://groups.google.com/forum/#!forum/weewx-development). 

Make sure you look at the section [*Porting to new hardware*](http://www.weewx.com/docs/customizing.htm#porting
) in the Customizing Guide.
