### ISSUE TITLE
Customised units in skin.conf

### ISSUE THREAD

**Issue by mbradley612** [weewx/weewx#523]
weewx version 3.9.2

I've tried customising units within skin.conf. The config doesn't appear to be picked up. Initially it was my own skin, I'm getting the same behaviour with the Seasons skin.

Configuration in skin.conf:

```
[Units]
[[Groups]]
group_speed = meter_per_second
group_speed2 = meter_per_second2

```

Can you advise if this is a bug of if I am doing something wrong.

I have achieved my desired goal by setting the units I want within weewx.conf defaults.

**Comment by tkeffer** [comment]
Options specified in the `skin.conf` files are overridden by options in `weewx.conf`.  See the section [How options work](http://www.weewx.com/docs/customizing.htm#How_options_work) in the Customizing Guide.
