### ISSUE TITLE
"Aggregation" Option, not available in configuration file

### ISSUE THREAD

**Issue by mirtaheri** [weewx/weewx#529]
Hello!
For mqtt extension, I guess to set the `aggregation` option there is no choice unless changing it directly in `mqtt.py`, right in the class `MQTTThread`, I didn't find any other solution from documentation and did so (please correct me if I am wrong). Since in some cases (like mine) the preference is `aggregate` rather than `individual`, wouldn't be better to have this option available in `weewx.config` in the `[[MQTT]]` field?

Best regards,
Hamid

**Comment by tkeffer** [comment]
Hello,

The mqtt extension is not actually part of WeeWX. You will have to ask the extension author.
