### ISSUE TITLE
Numerous syntax error running forecast.py due to Python versions on raspbian "Buster"

### ISSUE THREAD

**Issue by TonyF21** [weewx/weewx#540]
Hi,

Installed Weewx 4.0.0 on raspbian "Buster", latest release.  I can install the forecast extension but when it runs giving numerous syntax errors.  Was able to mix most issues using converter script 2to3 for Python.  There remains an issue with line 1186.
File "/usr/share/weewx/user/forecast.py", line 1186, in update_forecast
May  7 22:10:12 WXraspberrypi weewx[14725] CRITICAL __main__:     ****      elif time.time() - self.interval > self.last_ts:
May  7 22:10:12 WXraspberrypi weewx[14725] CRITICAL __main__:     ****  TypeError: '>' not supported between instances of 'float' and 'NoneType'

"Buster" has two version of python installed.
2.7.16
3.7.3

I forced it to default and use 2.7.16 but still having issue.  Any plans to port this great extension over to newest raspbian?

Thank you,

TonyF

**Comment by tkeffer** [comment]
The forecast module is not actually part of WeeWX. However, I believe this is a known problem. Take a look at this thread in weewx-user: https://groups.google.com/forum/#!topic/weewx-user/iciMc4UeOjk
