### ISSUE TITLE
Working with Weewx 4 & Python 3

### ISSUE THREAD

**Issue by danielforster** [weewx/weewx#545]
Hello,

I see there is a big green tick next to this plugin saying it is compatible with Weewx 4 on Python 3. 

Following the instructions therefor, I need to install Pip (not Pip3, even though my system (RPi 4 with Buster) runs Python 3)), and then install the plugin? Or Will this work with Pip3?

Cheers

Dan

**Comment by tkeffer** [comment]
This issues list is for tracking bugs in WeeWX. Please direct your question to [weewx-user](https://groups.google.com/forum/#!forum/weewx-user).
