### ISSUE TITLE
WEEWX_ROOT not set correctly when install with setup.cfg on 4.0.0

### ISSUE THREAD

**Issue by g-eddy** [weewx/weewx#546]
unpacked weewx-4.0.0, updated config.cfg "home = /home/weewx" to "home = /opt/weewx-4.0.0", ran setup.py build and setup.py install, resultant /opt/weewx-4.0.0/weewx.conf had "WEEWX_ROOT = /home/weewx" i.e. unchanged.
did this on my test host then server host, same results

**Comment by g-eddy** [comment]
correction: updated setup.cfg *doh!*

**Comment by tkeffer** [comment]
Right you are! The setup program neglected to set it.

Fixed in commit https://github.com/weewx/weewx/commit/8248bd489441de496b24b7bba9da6862b6d2defa
