### ISSUE TITLE
Feature Request for Vantage : Add the iss transmitter id and archive interval to the station

### ISSUE THREAD

**Issue by Hyrules** [weewx/weewx#548]
In the Cheetah engine it's possible to get some information about the station using the $station variable. Missing from the station information is the iss transmitter id for wireless station and the archive interval. Those value are reported by the wee_device. 

Thanks for considering this.

**Comment by tkeffer** [comment]
The archive interval can change. The current interval can be obtained from `$current.interval`.

The ISS number is unique to the Vantage series. Other hardware does not have such a concept. You would need to write a search list extension for it.
