### ISSUE TITLE
Error in Forecast.py under version 4 

### ISSUE THREAD

**Issue by redcardan104** [weewx/weewx#555]
File "/usr/share/weewx/user/forecast.py", line 1212, in update_forecast
May 20 09:00:21 weatherpi weewx[15068] CRITICAL __main__:     ****      elif time.time() - self.interval > self.last_ts:
May 20 09:00:21 weatherpi weewx[15068] CRITICAL __main__:     ****  TypeError: '>' not supported between instances of 'float' and 'NoneType'

**Comment by tkeffer** [comment]
I'm sorry, but forecast is not part of WeeWX. You should post your note on the forecast website: https://github.com/weewx/weewx/wiki/forecasting

**Comment by redcardan104** [comment]
Thank you

 

Dan

 <mailto:dan@done-that.com> dan@done-that.com

When you have what you need, use the rest to bring joy into someone else’s life -Firoozeh Dumas

If you can afford it and the other can not, you pick up the check – Irv Freedman
