### ISSUE TITLE
Python3 conversion has completely forgotten about rainmachine.py

### ISSUE THREAD

**Issue by bigjools** [weewx/weewx#562]
I've installed the debian buster packages on Ubuntu 20.04. It won't start.

Upon investigation, the interpreter was complaining about mixing tabs and spaces for indentation (!) and after I fixed that, it was apparent that the code is still using Python 2 imports (`import Queue` for example).

**Comment by bigjools** [comment]
`/usr/share/weewx/user/rainmachine.py` is the bad file.

**Comment by tkeffer** [comment]
`rainmachine` is not part of WeeWX. You should contact the author.

**Comment by bigjools** [comment]
Apologies, my bad! I installed it so long ago that I forgot.

**Comment by tkeffer** [comment]
I had nothing better to do, so I forked it, then tried a quick port. Take a look at https://github.com/tkeffer/rainmachine-weewx.
