### ISSUE TITLE
MQTT allways closed after sending data

### ISSUE THREAD

**Issue by Wildbill-Z** [weewx/weewx#568]
Hi,
I tried to get data from weewx to a smarthome system called iobroker which also has a MQTT-Client. All worked well, but it seems, that the connection is allways closed after sending data and reopend new when next packet is ready. This causes the MQTT-Adapter in iobroker to display a (wrong) faulty state and allways writing a message in the log (see below).
Is there a chance to get the weewx-mqtt-adapter to not close the connection after sending?
Here my log in iobroker:
`

mqtt.0 | 2020-06-07 20:51:15.323 | info | (27911) Client [weewx_5d5f1a2c] connection closed: disconnected
-- | -- | -- | --
mqtt.0 | 2020-06-07 20:51:15.284 | info | (27911) Client [weewx_5d5f1a2c] connected with secret 1591555875283_6890
mqtt.0 | 2020-06-07 20:50:15.314 | info | (27911) Client [weewx_f6d54340] connection closed: disconnected
mqtt.0 | 2020-06-07 20:50:15.281 | info | (27911) Client [weewx_f6d54340] connected with secret 1591555815280_2309
mqtt.0 | 2020-06-07 20:49:15.327 | info | (27911) Client [weewx_295950fc] connection closed: disconnected
mqtt.0 | 2020-06-07 20:49:15.280 | info | (27911) Client [weewx_295950fc] connected with secret 1591555755279_2078
mqtt.0 | 2020-06-07 20:48:15.327 | info | (27911) Client [weewx_6f85f9bc] connection closed: disconnected
mqtt.0 | 2020-06-07 20:48:15.276 | info | (27911) Client [weewx_6f85f9bc] connected with secret 1591555695276_1289

`
Log in weewx is unsuspicious and all is working well, all data seems plausible and correct. Only the wrong state in iobroker and the log messages (which I could remove by setting log level to warn or error but thats not the point) are a bit of disturbing to me.
Greetings, Jürgen

**Comment by tkeffer** [comment]
Hello, Jürgen.

Unfortunately, the mqtt adapter is not part of WeeWX. You'll have to talk to its author.
