### ISSUE TITLE
windDir missing from archive records

### ISSUE THREAD

**Issue by weswitt** [weewx/weewx#584]
i have an issue where windDir values are not being included in archive records. i can see that the windDir values are being received by weewx loop packets. i can run weewxd and see the windDir values in the loop packets and then a value of "None" in the archive records.

why are the values not included in the archive records?

**Comment by tkeffer** [comment]
See the documentation: http://weewx.com/docs/usersguide.htm#zero_windspeed

**Comment by weswitt** [comment]
that doc does not directly apply.

my windspeed values are in fact NOT zero. after reading the weewx code i discovered that how the wind values are presented in the loop packets matters. i was creating separate loop packets for windspeed and winddir, which i think caused weewx to believe that the speed is zero when processing the winddir. i changed my driver to deliver a single loop packet that includes both windSpeed and windDir.  this seems to have resolved the issue as  i now see windDir values in my archive records.
