### ISSUE TITLE
Icons in Seasons for forecast single strip vertical are hughe

### ISSUE THREAD

**Issue by SylvainGa** [weewx/weewx#594]
Hi, installed the forecast plugin yesterday. I added the strip view to the Seasons skin. In its horizontal orientation, it works very well ([https://i.imgur.com/HR5jX81.png](https://i.imgur.com/HR5jX81.png)). However, when installed vertically, the icons take about half the web page ([https://i.imgur.com/fFnbG6q.png](https://i.imgur.com/fFnbG6q.png)).

Hitting http://x.x.x.x/weewx/forecast/single-strip-vertical.html displays the icons correctly ([https://i.imgur.com/sluJhF6.png](https://i.imgur.com/sluJhF6.png))

Anybody knows how to fix this? All my attempts prove unsuccessful :-(
 
Here's the relevant (I think) info from my latest attempt.

Platform Linux-4.19.118-v7+-armv7l-with-debian-10.4 running on a Raspberry 3
Python 2.7.16 (default, Oct 10 2019, 22:02:15) #012[GCC 8.3.0]
weewx version 4.1.1
forecast version 3.4.0b1

Relevant lines added in weewx.conf
```
[Forecast]
    data_binding = forecast_binding
    [[OWM]]
        api_key = ...

[StdReport]
    [[SeasonsReport]]
        # Forecast added to Seasons
        [[[CheetahGenerator]]]
            search_list_extensions = user.forecast.ForecastVariables
        [[[CopyGenerator]]]
            copy_once = seasons.css, seasons.js, favicon.ico, font/*.woff, font/*.woff2, forecast_strip.css, icons/*
```

Relevant lines added in the [Extras] of Seasons/skin.conf
```
    [[forecast_strip_settings]]
        source = OWM
        num_periods = 40
        show_temp = 1
        show_temp_min = 1
        show_temp_max = 1
        show_dewpoint = 0
        show_humidity = 0
        show_wind = 1
        show_clouds = 1
        show_pop = 1
        show_snow = 1
        show_precip = 1
        show_sun = 0
        show_moon = 0
        show_moonphase = 0
        show_tides = 0
```

Relevant lines added to Seasons/index.html.tmpl
```
    <div id="contents">
      <div id="widget_group">
        #include "current.inc"
        #include "sunmoon.inc"
        #include "hilo.inc"
        #include "sensors.inc"
        #include "radar.inc"
        #include "satellite.inc"
        #include "map.inc"
        #include "forecast.inc"
        #include "about.inc"
      </div>
```

New Seasons/forecast.inc script:
```
## forecast module for weewx skins
## Copyright Tom Keffer, Matthew Wall
## See LICENSE.txt for your rights
#errorCatcher Echo

<link rel='stylesheet' type='text/css' href='forecast.css'/>
<link rel='stylesheet' type='text/css' href='forecast_strip.css'/>

<div id='forecast_widget' class="widget">
  <div class="widget_title">
    Forecast
    <a class="widget_control"
      onclick="toggle_widget('forecast')">&diams;</a>
  </div>
  <div class="widget_contents" id='forecast_strip'>
    #set global $forecast_strip_settings = dict()
    #set global $forecast_strip_settings['orientation'] = 'vertical'

    #include "forecast_strip.inc"
    <script>
      populate_strip('forecast_strip', 'OWM');
    </script>
  </div>
</div>
```

File forecast_strip.inc,  forecast_strip.css and forecast.css are left intact and copied to Seasons from forecast as well as the icons

Thanks.

**Comment by tkeffer** [comment]
Hello. This issues list is for WeeWX bug reporting and tracking. The forecast extension is not part of WeeWX. 

I would suggest directing your question to either [weewx-user](https://groups.google.com/forum/#!forum/weewx-user), or to the author of the extension.
