### ISSUE TITLE
Support for multiple station_types

### ISSUE THREAD

**Issue by ituri** [weewx/weewx#595]
Hi,

I'm collecting weather data from numerous sources. In my case I would like to gather temperature data from some 433Mhz sensors via weewx-sdr but I also have a rain gauge that feeds into a mqtt broker which requires me to use WeeWX-MQTTSubscribe. As far as I understand, I am however only able to set _one_ station_type in my weewx.conf - either the one for sdr or for mqtt. Is there also the option to use data from multiple sources?

Thanks!

**Comment by tkeffer** [comment]
This issues list is for bug tracking and reporting for WeeWX. You should direct your question to [weewx-user](https://groups.google.com/forum/#!forum/weewx-user).
