### ISSUE TITLE
Document anti-aliasing feature (SF: #43 )

### ISSUE THREAD

**Issue by alco28** [weewx/weewx#6]
Nick Dajda's anti-aliasing feature is included in V3.1. After testing it a bit, it needs to be documented.

[Note: pulled from sourceforge issue 43](https://sourceforge.net/p/weewx/tickets/43/)

**Comment by tkeffer** [comment]
Fixed in commit https://github.com/weewx/weewx/commit/2b723cdf24ab02dc17a401f89c750c3d52728316

**Comment by gjr80** [comment]
Well, other than reading the title, I always wondered what this did.

**Comment by tkeffer** [comment]
Did you see the cool [GIF](https://github.com/weewx/weewx/blob/2b723cdf24ab02dc17a401f89c750c3d52728316/docs/images/antialias.gif) that illustrates?

**Comment by gjr80** [comment]
Yep, that was what did it for me!
