### ISSUE TITLE
Forecasting Extension (v 3.4.0b1) Crash at Report Interval

### ISSUE THREAD

**Issue by dotJson** [weewx/weewx#605]
Functional install, added forecasting extension (from https://github.com/matthewwall/weewx-forecast/archive/master.zip) and only enabled the WU with an API key in weewx.conf.  Restarted service and (with debug=1) the syslog generates the following:

At restart it looks normal:

> Sep 10 21:40:15 weewx weewx[967] DEBUG weewx.engine: Loading service user.forecast.WUForecast
> Sep 10 21:40:15 weewx /weewxd: forecast: MainThread: WU: forecast version 3.4.0b1
> Sep 10 21:40:15 weewx /weewxd: forecast: MainThread: WU: interval=10800 max_age=604800 api_key=XXXXXXXXXXXXXXXXXXXXXXXXXXXX6894 location=33.3079221,-111.6236882 fc=hourly10day
> Sep 10 21:40:15 weewx weewx[967] DEBUG weewx.engine: Finished loading service user.forecast.WUForecast

Then at interval reporting:

> Sep 10 21:35:34 weewx weewx[807] DEBUG user.weather34: do_file_transfer: Rsync complete
> Sep 10 21:35:34 weewx weewx[807] INFO weewx.manager: Added record 2020-09-10 21:35:00 MST (1599798900) to daily summary in 'weewx.sdb'
> Sep 10 21:35:34 weewx weewx[807] INFO weewx.engine: Main loop exiting. Shutting engine down.
> Sep 10 21:35:34 weewx weewx[807] DEBUG weewx.restx: Shut down AWEKAS thread.
> Sep 10 21:35:34 weewx weewx[807] DEBUG weewx.restx: Shut down WOW thread.
> Sep 10 21:35:34 weewx weewx[807] DEBUG weewx.restx: Shut down CWOP thread.
> Sep 10 21:35:34 weewx weewx[807] DEBUG weewx.restx: Shut down Wunderground-RF thread.
> Sep 10 21:35:34 weewx weewx[807] DEBUG weewx.restx: Shut down StationRegistry thread.
> Sep 10 21:35:34 weewx weewx[807] INFO user.interceptor: shutting down server thread
> Sep 10 21:35:34 weewx weewx[807] DEBUG user.interceptor: stop tcp server
> Sep 10 21:35:34 weewx weewx[807] CRITICAL __main__: Caught unrecoverable exception:
> Sep 10 21:35:34 weewx weewx[807] CRITICAL __main__:     ****  '>' not supported between instances of 'float' and 'NoneType'
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****  Traceback (most recent call last):
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 195, in run
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.CHECK_LOOP, packet=packet))
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****      callback(event)
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 578, in check_loop
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****      raise BreakLoop
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****  weewx.engine.BreakLoop
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****  During handling of the above exception, another exception occurred:
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****  Traceback (most recent call last):
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 594, in post_loop
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****      self._catchup(self.engine.console.genArchiveRecords)
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 638, in _catchup
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****      for record in generator(lastgood_ts):
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/drivers/__init__.py", line 30, in genArchiveRecords
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****      raise NotImplementedError("Method 'genArchiveRecords' not implemented")
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****  NotImplementedError: Method 'genArchiveRecords' not implemented
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****  During handling of the above exception, another exception occurred:
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****  Traceback (most recent call last):
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 154, in main
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****      engine.run()
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 202, in run
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****      self.dispatchEvent(weewx.Event(weewx.POST_LOOP))
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****      callback(event)
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 596, in post_loop
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****      self._software_catchup()
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 658, in _software_catchup
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****      origin='software'))
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 224, in dispatchEvent
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****      callback(event)
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****    File "/usr/share/weewx/user/forecast.py", line 1212, in update_forecast
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****      elif time.time() - self.interval > self.last_ts:
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****  TypeError: '>' not supported between instances of 'float' and 'NoneType'
> Sep 10 21:35:35 weewx weewx[807] CRITICAL __main__:     ****  Exiting.
> 

I'm not even sure where to begin so I uninstalled the Forecast extension and restarted.  No more crash.

**Comment by tkeffer** [comment]
This issues list is for reporting and tracking of bugs in WeeWX. The forecasting module is not part of WeeWX. You would have better luck either trying [weewx-user](https://groups.google.com/forum/#!forum/weewx-user), or the issues list for the forecasting module.
