### ISSUE TITLE
Label on right side of graphs

### ISSUE THREAD

**Issue by brentfraser** [weewx/weewx#609]
I find it inconvenient that the graph's y-axis labels are on the left but the latest data is on the far right side, so my eye has to follow the grid lines over to the left to estimate the values.   A simple solution is put labels on the right side as well, like so:

![image](https://user-images.githubusercontent.com/1638313/94345709-303b2e80-ffe5-11ea-94a3-d03fb1d92c2c.png)

I've changed `genplot.py` to widen the right margin:
```
        self.rmargin = int(4.0 * self.axis_label_font_size)
```

and to label the right y-axis:

```
                sdraw.draw.text( (self.lmargin - axis_label_size[0] - 2, ypos - axis_label_size[1]/2),
                                ylabel, fill=self.axis_label_font_color, font=axis_label_font)
                # label right 
                sdraw.draw.text( (self.image_width - self.rmargin + 4, ypos - axis_label_size[1]/2),
                                ylabel, fill=self.axis_label_font_color, font=axis_label_font)
```

But I suppose, in preparation of a pull request, I should add code to make it optional.  As a newbie, I'm not sure the best way to do that.  An option in the skin.conf like:

`  y_label = left, right`

with the default `= left`

Opinions?

**Comment by richardh9935** [comment]
Good idea. Australian Bureau of Statistics swapped to the right-sided Y-axis in the 1980's for exactly that reason. 
Richard.

**Comment by tkeffer** [comment]
That seems reasonable: `left`, `right`, or `both`

**Comment by brentfraser** [comment]
I had to add a little bit of code to move the units label
![image](https://user-images.githubusercontent.com/1638313/94373940-04dc4080-00c6-11eb-97ef-0badf8d97cf7.png)

And change the parameter name:

`		y_label_side = both
`
