### ISSUE TITLE
Weewx on OpenWrt doesn't work with Davis Envoy

### ISSUE THREAD

**Issue by vlad4990** [weewx/weewx#616]
Hello. I have OpenWrt device with installed Openwrt. It works with Vantage pro 2 Console and Vantage vue Console, But doesn't work  with Davis Envoy(6316). I get an error: "weewx.WakeupError: Unable to wake up Vantage console". I have already installed pySerial package, it doesn't help.
In other thread(#293) i found this test script:
```
import serial
port = serial.Serial("/dev/ttyUSB0", 19200)

port.write("WRD" + chr(0x12) + chr(0x4d) + "\n")

ack = port.read()
if ack != chr(0x06):
    print "Unable to get ACK. Got %d instead." % ack

htype = port.read()

print "Hardware type is %d" % htype
port.close()
```

But she stops at the line: "ack = port.read()" , it cannot run line, however it doesn't show me any errors, it just hangs.

Envoy use USB data logger and have this name in system - /dev/ttyUSB0
someone faced this problem, or can help with any advice?
Thanks in advance to everyone!

**Comment by tkeffer** [comment]
Hello. This list is for bug tracking. 

Please post to [weewx-user](https://groups.google.com/forum/#!forum/weewx-user).
