### ISSUE TITLE
WMR200 driver calculates dayRain incorrectly

### ISSUE THREAD

**Issue by tkeffer** [weewx/weewx#62]
The type `dayRain` should be the rain since midnight, but the WMR200 driver actually emits the rain over the last 24 hours, excluding the current hour.

**Comment by tkeffer** [comment]
Tentative fix in commit 5cc0e71d64967eacdaeaa3bbbdc4ce367aa5535a. Checking with user.

**Comment by rothlive** [comment]
Thanks Tom the driver fix is very good.
All works fine.
The set to 0 after  Midnight works.

**Comment by tkeffer** [comment]
To appear in V3.3.0
