### ISSUE TITLE
'_get_ephem_body' fails for heavenly bodies containing spaces

### ISSUE THREAD

**Issue by bbseal** [weewx/weewx#620]
Hi,

Forgive me if I'm missing anything; this is the first issue I have filed.

In the `_get_ephem_body` function of `almanac.py`, the name of the heavenly body argument that is passed to the function is capitalized using the `.capitalize()` method.  This causes lookup errors for heavenly bodies containing spaces because it only capitalizes the first letter in the string.  There are a handful of stars in the [pyephem star database](https://github.com/brandon-rhodes/pyephem/blob/master/ephem/stars.py) that contain spaces and require all words to begin with capital letters.

On my 4.2.0 installation I changed the `.capitalize()` method to the `.title()` method, and this solved the problem since it capitalizes the first letter of all the words in the string.

Hope this is the proper way to submit things.  You guys are awesome.  Cheers.

**Comment by tkeffer** [comment]
Thanks Jared! I wish all problems were this easy to fix.

Commit https://github.com/weewx/weewx/commit/737c4dfe0ee8235650aa91d4d4a15afd7a9d3678
