### ISSUE TITLE
Wee_config with no options gives "internal logic error"

### ISSUE THREAD

**Issue by PeterQuinn925** [weewx/weewx#622]
When I run wee_config and give it the path to the weewx.conf file but no other options, it gives the error "internal logic error in config.py"

It really should say something like, "try using an option like --install or --reconfigure" rather than just say it's a logic error. 

It's an extremely minor problem, but I thought I'd note it (and put in a pull request if you'd like)

**Comment by tkeffer** [comment]
Fixed in commit https://github.com/weewx/weewx/commit/79f9133df3abc4378eabbc01a2562fb04e9e65c3
