### ISSUE TITLE
(upgrade guide) better explain how to answer dpkg prompts

### ISSUE THREAD

**Issue by vinceskahan** [weewx/weewx#634]
The Upgrade Guide documents what the user will see when they upgrade a dpkg installation, but the descriptions of what will happen (and what the user needs to do manually) are somewhat cryptic and a bit confusing.

Suggest enhancing the docs a bit in the context of upgrading a weewx system that has a previously installed extension that added a skin and service to weewx.conf - what does the user need to actually do for the Y/N/D/Z possible answers ?

(this is a nice-to-have, not a bug report)

**Comment by tkeffer** [comment]
Done in commit https://github.com/weewx/weewx/commit/f90473fb97909a80151d097f6f9799c26bba798c
