### ISSUE TITLE
Improved handling of diacritics in `strict_ascii` encoded reports

### ISSUE THREAD

**Issue by gjr80** [weewx/weewx#644]
When generating `strict_ascii` encoded reports the Cheetah Generator removes any characters from the report output that cannot be converted to an ASCII equivalent. This means that accented characters in, for example,  station locations in the NOAA format reports are removed and can result in unexpected results. This is a limitation of the existing Cheetah Generator where (for `strict_ascii` encoding) the Cheetah unicode output is simply encoded as ASCII and any errors ignored, ie `unicode_string.encode('ascii', 'ignore')`

A better approach would be to replace any accented characters with a non-accented equivalent. Whilst some detail is lost the intended result can usually be inferred from the replacement text.

[This weewx-user post](https://groups.google.com/g/weewx-user/c/I0FnvFdBlqk/m/bAgrDnNLAAAJ) refers.

**Comment by tkeffer** [comment]
Fixed in commit https://github.com/weewx/weewx/commit/adaf4d920b67e2f587cdf27e330eca763b20e85c
