### ISSUE TITLE
Updates to PWSWeather are sent as plaintext

### ISSUE THREAD

**Issue by genesispc** [weewx/weewx#650]
Looking through my router log I noticed that updates to PWSWeather are sent as plaintext, meaning that the password used to update the values is visible to all. Can I suggest changing the following line (line 720) in /bin/weewx/restx.py

from:

    archive_url = "http://www.pwsweather.com/pwsupdate/pwsupdate.php"

to

    archive_url = "**https**://www.pwsweather.com/pwsupdate/pwsupdate.php"

I've tried it locally and it works a treat.

**Comment by chaunceygardiner** [comment]
I tested this change, and also changed the URL for WOW (in the same file) to use https.  Both worked for me.  It looks like the others are already using https.

**Comment by tkeffer** [comment]
Fixed in commit https://github.com/weewx/weewx/commit/bada58c979fa8572391657960cd3c993c28c4f00

Thanks, @genesispc  for the fix, and John (@chaunceygardiner) for testing it!
