### ISSUE TITLE
Add another weather forecasting service

### ISSUE THREAD

**Issue by dtalens** [weewx/weewx#656]
Is it possible to use another weather forecasting service?
I would like to use AEMET (State Meteorological Agency of Spain), but my knowledge of python is very limited.
I can help translate the API into English.

Exists AEMET API, more information: 
https://opendata.aemet.es/centrodedescargas/inicio
https://opendata.aemet.es/dist/index.html

Thanks,

**Comment by tkeffer** [comment]
The issues list is for tracking WeeWX bugs. The forecast extension is not part of WeeWX. You'd have better luck posting over there.
