### ISSUE TITLE
Upgrade six.py

### ISSUE THREAD

**Issue by lniles77** [weewx/weewx#657]
Weewx distributes six.py version 1.12.0.  The current version is (at least) 1.15.0, and includes some new functionality, in particular, support for collections.abc which were introduced in python 3.3.   I hit this when I built a ReportGenerator that uploads some weewx data to a google spreadsheet; the google API client uses collections.abc.  

As a work-around I deleted the weewx-installed six.py, since the google API install installs six.py in a library path. But it would be nice to not have to do this.  I've had no issues with weewx 4.4 running on six.py 1.15.0.

**Comment by tkeffer** [comment]
Good idea. Fixed in commit https://github.com/weewx/weewx/commit/bde354aa713996de6a1791a7f1c8f815df3c8cc0
