### ISSUE TITLE
Retrieve weather station location from a GPS

### ISSUE THREAD

**Issue by JoseGoncalves** [weewx/weewx#666]
I'm using weewx in a custom mobile weather station (based on a Airmar device) which has a GPS device builtin.
I would like to set dynamically the weather station's Latitude/Longitude/Altitude in the weewx web page from the GPS device instead of the setting it statically from the configuration file.
Can anyone give me some pointers on best way(s) to achieve that?

**Comment by tkeffer** [comment]
The issues list is for bug reporting and tracking. Try posting to the user group, [weewx-user](https://groups.google.com/forum/#!forum/weewx-user).
