### ISSUE TITLE
Rain rate and rate data false

### ISSUE THREAD

**Issue by EDDM-01** [weewx/weewx#680]
Since two weeks, I have the issue that the rain rate and data are horribly wrong.

I always get the following data shown up in the summit:

For instance:
10592,6 mm Rain weekly - 
42370,2 mm/h - rain rate
June 2021: 21248,4 mm

The amount of rain is correctly shown on the display of my weather station.

Can anyone tell me how I can fix this problem? And of course correct or delete the wrong records?

If you need more information, just let me know.

Best regards and thank you!
Mike

**Comment by tkeffer** [comment]
Cross-posted to weewx-user.
