### ISSUE TITLE
Persistent "dict" for "Accum" class?

### ISSUE THREAD

**Issue by simplegui-helper** [weewx/weewx#682]
I'm a new user of "weewx". I'm not sure, but it appears that when "weewx" is restarted, it looses the accumulated data for the archive period.

Would it be possible to create a persistent "dict" object for use with the "Accum" class so it can be reused when "weewx" is restarted instead of creating a new accumulator?

**Comment by tkeffer** [comment]
Such a class would be useful only when WeeWX was stopped, then restarted, within an archive period. Even then, it would lose some LOOP packets. There's also the question of when this modified Accum would save state. After every LOOP packet? When given a TERM signal? That's a lot of extra complexity for marginal benefit in a rare case.
S
