### ISSUE TITLE
REST API?

### ISSUE THREAD

**Issue by hemna** [weewx/weewx#697]
Is there a REST API into weewx?  I'm looking around and don't see one.  Sure would be nice to ask weewx what the latest wx data was from an external app.

**Comment by tkeffer** [comment]
Many users have been using MQTT extensions to do this. Look through the wiki. https://github.com/weewx/weewx/wiki

In the future, please use the [weewx-user](https://groups.google.com/forum/#!forum/weewx-user) group for general inquiries. We use the issues list for tracking bugs and features.
