### ISSUE TITLE
Problem measure temps above 120 farenheit

### ISSUE THREAD

**Issue by putteg** [weewx/weewx#707]
Hi, It seems like there are a problem measure temperatures above 120°F (49°C)
If we reach this temperature and above it gives 0°C in the csv file (and mysqlDB).

![Weather](https://user-images.githubusercontent.com/29883094/138220225-0636b381-d3ef-4f2f-a623-7693f6f4bfaa.png)

**Comment by gjr80** [comment]
Most likely you are using the default `StdQC` min/max limits for `outTemp` which are -40, 120 degree_F. So any `outTemp` value outside these limits will be set to `None`. Likely all you need to do is increase the max value. Refer to the [[StdQC] [[minmax]] section](http://weewx.com/docs/usersguide.htm#%5B%5BMinMax%5D%5D) in the User's Guide.

Also, this issues list is for WeeWX bug reporting and tracking. If the above link does not help please post to [weewx-user](https://groups.google.com/g/weewx-user).
