### ISSUE TITLE
`wee_import` documentation needs minor revision 

### ISSUE THREAD

**Issue by gjr80** [weewx/weewx#710]
The `interval` option in the import config file is ignored if a field named `interval` exists in the data to be imported. This is by design but is not documented in the `wee_import` documentation.

Refer [this weewx-user thread](https://groups.google.com/g/weewx-user/c/ZHG7Ntm9rWI/m/T_q12-uAAwAJ).

**Comment by gjr80** [comment]
Been thinking about this overnight and I am now wondering if the processing of the `interval` option is correct. 

At present if the import source data has no `interval` field the `interval` field for the imported data is derived as per the `interval` import config option. However, if the import source data does indeed have an `interval` field that data is used for the `interval` field for the imported data and the `interval` import config option is ignored. So in the corner case where the import source data has an `interval` field but the user does not want to use it, the user must remove the `interval` data from the source data before importing and set the `interval` import config option accordingly.

Perhaps the behaviour of the `interval` import config option should be changed such that it takes precedence over any source data `interval` field and it must be left blank or set to, say, 'field' to use the `interval` field in the source data (if it exists). Or do we just leave things as they are and add a few more words to the docs explaining the use of the `interval` field (if it exists) and be done with it. Or do we do something else?

**Comment by tkeffer** [comment]
If the user specifies an `interval`, then I would think that should always take precedence. 

I like the idea of offering an explicit option to use the `interval` field in the import data, then make it the default. So, the options would be
- `x`, where `x` is the number of minutes
- `conf`
- `field`. Or, maybe `source`? You already use that term elsewhere.
