### ISSUE TITLE
Acurite intermittent calculation of barometer

### ISSUE THREAD

**Issue by bwarden** [weewx/weewx#714]
Executive Summary: When using the Acurite driver, because barometer is calculated from absolute pressure and outside temperature, it will only be reported when both readings are available simultaneously.

[Originally posted in weewx-users](https://groups.google.com/g/weewx-user/c/pbJyKmYy3mA/m/Hsk9AWaSCQAJ)

This has been bugging me for a few years, but I just haven't been able to figure out where/how to fix it best. In the Acurite driver, there are 3 different data packets (and two variants of one of those), each updated at different intervals (18, 60, and 12*60 seconds)  Indoor air pressure is reported in R2, while outside temperature is reported in alternating R1 variants. This means that we *often* don't have a current reading for outside temperature at the same time we get a pressure reading, especially if the USB connection is being finicky, which is common with Acurite hardware.

As a result, there can be long intervals (I've seen 10+ minutes) between successful barometer calculations. When generating static webpages or otherwise working from archive data, this isn't a huge issue. When trying to do something near-real-time with loop data (for example MQTT to Home Assistant), though, this can be really annoying.

**Comment by tkeffer** [comment]
Addressed in PR #716
