### ISSUE TITLE
Weewx and WMR200: adding a service automatic restart?

### ISSUE THREAD

**Issue by zoomx** [weewx/weewx#718]
Since WMR200 is not supported anymore and since non solution was found what about adding

Restart=always
RestartSec=3

in weewx.service in order to have the system restart it when closes for USB error?

**Comment by tkeffer** [comment]
You can certainly add it to your copy, but this is a bit too much policy for the general distribution. For one thing, because the weewx daemon forks, systemd cannot always detect a failure.

More experimentation would be needed.
