### ISSUE TITLE
Docs: Configuring the html lang tag

### ISSUE THREAD

**Issue by glennmckechnie** [weewx/weewx#749]
https://weewx.com/docs/customizing.htm#Internationalize_the_template

To change the html lang attribute in the html file the docs indicate that **$gettext** is used. This is incorrect.

Just using **$lang** is required (as defined in the appropriate weewx.conf section.)

----

"At the top of the template, change the HTML "lang" attribute to a configurable value."

Currently it states this...

```
<!DOCTYPE html>
<html lang="$gettext("lang")">
  <head>
    <meta charset="UTF-8">
    ...
```

When it should be...

```
<!DOCTYPE html>
<html lang="$lang">
  <head>
    <meta charset="UTF-8">
    ...
```

**Comment by tkeffer** [comment]
Fixed.

Thanks, Glenn.
