### ISSUE TITLE
AttributeError: 'ImageGenerator' object has no attribute 'generic'

### ISSUE THREAD

**Issue by Mkamaro** [weewx/weewx#752]
Today I updated my "weewx" installation from version 4.5.1 to 4.6.2.
After my own service ran the first time I found the following error message in the log:
`weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 197, in run`
`weewx.reportengine:         ****      obj.start()`
`weewx.reportengine:         ****    File "/home/weewx/bin/weewx/reportengine.py", line 378, in start`
`weewx.reportengine:         ****      self.run()`
`weewx.reportengine:         ****    File "/home/weewx/bin/user/My_own_service.py", line 1594, in run`
`weewx.reportengine:         ****      g.run()`
`weewx.reportengine:         ****    File "/home/weewx/bin/weewx/imagegenerator.py", line 41, in run`
`weewx.reportengine:         ****      self.setup()`
`weewx.reportengine:         ****    File "/home/weewx/bin/weewx/imagegenerator.py", line 49, in setup`
`weewx.reportengine:         ****      self.generic.dict = {}`
`weewx.reportengine:         ****  AttributeError: 'ImageGenerator' object has no attribute 'generic'`
`weewx.reportengine:         ****  Generator terminated`

I think the problem is line 49 of the file "imagegenerator.py". I changed the line from "self.generic.dict = {}" to "self.generic_dict ={}" and solved the problem for me.

Thanks for the great program
Greetings

**Comment by tkeffer** [comment]
Thanks, Mkamaro! Fixed in commit https://github.com/weewx/weewx/commit/e0ca8cb40b8c60c5a7f2aad901a7105503b4b869
