### ISSUE TITLE
weewx multi: config generation according to driver for each instance possible?

### ISSUE THREAD

**Issue by fankyy** [weewx/weewx#754]
As far as i know the config file is generated to match the according driver. Is it possible to generate an according config file for each weewx instance after applying the weewx multi steps?

**Comment by tkeffer** [comment]
Any configuration file can be managed by `wee_config`. For example,

    wee_config --reconfigure /path/to/file.conf

In the future, please post queries to [weewx-user](https://groups.google.com/g/weewx-user). That way, others can see your query and contribute. This issues list is generally used for bug tracking.
