### ISSUE TITLE
Different strategy for "Expected 99, got 0" error with Vantage stations

### ISSUE THREAD

**Issue by tkeffer** [weewx/weewx#772]
Right now, if the Vantage driver gets this error, it retries 3 times, then gives up and restarts the program from the top.

An alternative would be something not quite so drastic: try the "wakeup" sequence. If that doesn't work, then do a program restart.

**Comment by PeterQuinn925** [comment]
I feel like [Jay-Z](https://www.youtube.com/watch?v=0YdLT0rL6L4) wrote this bug report

**Comment by tkeffer** [comment]
LOL! Can't help him with *that* problem.
