### ISSUE TITLE
WS23xxDriver error

### ISSUE THREAD

**Issue by kudumi** [weewx/weewx#785]
weewx status throws a bunch of error which I can't figure out. Could you please help me to fix them? (earlier, weewx was working fine, but I don't know if the current issue is related to new linux OS or weewx.) Any help is much appreciated, thank you.

$ /usr/bin/weewxd --version
4.8.0

$ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"

$ sudo /etc/init.d/weewx status
● weewx.service - LSB: weewx weather system
     Loaded: loaded (/etc/init.d/weewx; generated)
     Active: active (exited) since Tue 2022-08-09 09:41:22 IST; 5min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 399 ExecStart=/etc/init.d/weewx start (code=exited, status=0/SUCCESS)
        CPU: 1.700s

Aug 09 09:41:22 raspberrypi python3[558]: weewx[558] CRITICAL weewx.engine:     ****      return WS23xxDriver(config_dict=config_dict, **config_dict[DRIVER_NAME])
Aug 09 09:41:22 raspberrypi python3[558]: weewx[558] CRITICAL weewx.engine:     ****    File "/usr/share/weewx/weewx/drivers/ws23xx.py", line 439, in __init__
Aug 09 09:41:22 raspberrypi python3[558]: weewx[558] CRITICAL weewx.engine:     ****      self.station = WS23xx(self.port)
Aug 09 09:41:22 raspberrypi python3[558]: weewx[558] CRITICAL weewx.engine:     ****    File "/usr/share/weewx/weewx/drivers/ws23xx.py", line 641, in __init__
Aug 09 09:41:22 raspberrypi python3[558]: weewx[558] CRITICAL weewx.engine:     ****      self.serial_port = LinuxSerialPort(port)
Aug 09 09:41:22 raspberrypi python3[558]: weewx[558] CRITICAL weewx.engine:     ****    File "/usr/share/weewx/weewx/drivers/ws23xx.py", line 901, in __init__
Aug 09 09:41:22 raspberrypi python3[558]: weewx[558] CRITICAL weewx.engine:     ****      self.orig_settings = tty.tcgetattr(self.serial_port)
Aug 09 09:41:22 raspberrypi python3[558]: weewx[558] CRITICAL weewx.engine:     ****  termios.error: (22, 'Invalid argument')
Aug 09 09:41:22 raspberrypi python3[558]: weewx[558] CRITICAL __main__: Unable to load driver: (22, 'Invalid argument')
Aug 09 09:41:22 raspberrypi python3[558]: weewx[558] CRITICAL __main__:     ****  Exiting...

**Comment by tkeffer** [comment]
Hello,

The issues list is for bug reporting and tracking. For general support, please post to [weewx-user](https://groups.google.com/g/weewx-user).

Be sure to include a full log, not just a 'status' excerpt.
