### ISSUE TITLE
Logrotate rotation

### ISSUE THREAD

**Issue by sastorsl** [weewx/weewx#791]
The logrotate example relies on rsyslog to either discover the file to be gone or that you have to reload rsyslog.
This can be managed by the `copytruncate` directive for logrotate, which will copy the file first, then truncate it `cp /dev/null <file>`

**Comment by sastorsl** [comment]
Any comments to the issue or PR?

**Comment by tkeffer** [comment]
We're waiting for @matthewwall to review, but he is in Asia. Sorry for the delay!

**Comment by matthewwall** [comment]
`copytruncate` added at commit 229c80659fcd42cc645df97eecf510b376394b39

**Comment by sastorsl** [comment]
@matthewwall would you take a look at the PR in #792 ?
