### ISSUE TITLE
weewex deb intall fails to install files for web

### ISSUE THREAD

**Issue by JDJoe** [weewx/weewx#796]
Ubuntu 22.04.1 LTS
weewex install and starts but wont add directories to /home/ or /var/www/html/ 

Only file under home is: 
`/home/weewx/archive/weewx.sdb`

db is updated and it's visible in the log file 

`weewx[1238] INFO weewx.manager: Added record 2022-09-29 12:25:00 UTC (1664454300) to daily summary in 'weewx.sdb'`

I can assume it talks to the PWS and collects data.

**Comment by tkeffer** [comment]
The issues list is for bug reporting and tracking. Please direct your support question to [weewx-user](https://groups.google.com/g/weewx-user). When you do so, be sure to follow the guidelines [*Posting to weewx-user*](https://github.com/weewx/weewx/wiki/Help!-Posting-to-weewx-user) and include more of the log.

**Comment by JDJoe** [comment]
This is NOT a support question. This is me letting you know that the there is something wrong wit the installation process. 

You set up a support group for only those with a google mail account? How did you even come up with something as silly as that? 
I do not have google account and I wont be getting one.

**Comment by tkeffer** [comment]
Oh, calm down.

If this is a bug, we'll need more information. 

Please stop weewx, set `debug=1`, then restart. Run it through the first archive interval. Post the log from start up.

I also don't understand the phrase "I can assume it talks to the PWS and collects data." What do you mean by "the PWS?" The station console?

**Comment by tkeffer** [comment]
@JDJoe?
