### ISSUE TITLE
Minor Install Warning 4.9.0 Beta

### ISSUE THREAD

**Issue by gary-hammer** [weewx/weewx#799]
Installed weewx-4.9.0.tar.gz on my test server running Pop!_OS 22.04 LTS using setup.py method.
So far, only received a single error during setup itself.

`/usr/local/lib/python3.10/dist-packages/setuptools/dist.py:771: UserWarning: Usage of dash-separated 'exec-prefix' will not be supported in future versions. Please use the underscore name 'exec_prefix' instead
  warnings.warn(`

**Comment by tkeffer** [comment]
Thanks. I wish all issues were that easy to fi!
