### ISSUE TITLE
Can't reinstall

### ISSUE THREAD

**Issue by kevinkey619** [weewx/weewx#823]
I've uninstalled and now when I try to reinstall weewx, I get the below errors. Do I need to format the SD card and reinstall Raspberry Pi and weewx from scratch? 

Get:1 http://weewx.com/apt/python3 buster/main all weewx all 4.9.1-1 [1,838 kB]
Fetched 1,838 kB in 1s (3,467 kB/s)
Preconfiguring packages ...
Selecting previously unselected package weewx.
(Reading database ... 85483 files and directories currently installed.)
Preparing to unpack .../archives/weewx_4.9.1-1_all.deb ...
Unpacking weewx (4.9.1-1) ...
Setting up weewx (4.9.1-1) ...
update-rc.d: error: unable to read /etc/init.d/weewx
dpkg: error processing package weewx (--configure):
 installed weewx package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 weewx
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by matthewwall** [comment]
this issue system is for tracking bugs/features in weewx.  for support issues, please post to the weewx user group.
