### ISSUE TITLE
for aggregation of `wind` the reading of `windGust` is used for `max` but `windSpeed` for `maxtime`

### ISSUE THREAD

**Issue by roe-dl** [weewx/weewx#833]
In `xtypes.py` the derived observation type `wind` is replaced by `windGust` for the aggregation type `max` and by `windSpeed` for other aggregation types (see line 311). This means `...wind.max` is based on observation type `windGust` but `...wind.maxtime` is based on `windSpeed`. Is that intended?

**Comment by tkeffer** [comment]
You have an extraordinary eye for catching these things. I guess we want

``` python
        if obs_type == 'wind':
            sql_type = 'windGust' if aggregate_type in {'max', 'maxtime'} else 'windSpeed'
        else:
            sql_type = obs_type
```

**Comment by roe-dl** [comment]
> You have an extraordinary eye for catching these things. I guess we want

Sometimes people called me autistic. May be they are right a little bit. But in this case it was not me but @hoetzgit who found out.

**Comment by roe-dl** [comment]
I thought about other aggregation types that may be affected, but I found none. So I guess I send a PR about this.
