### ISSUE TITLE
4.10.1 ERROR in imagegenerator.py

### ISSUE THREAD

**Issue by blulite** [weewx/weewx#840]
There is an extra "f" in line 259 of  imagegenerator.py

```
diff imagegenerator.py imagegenerator.py.orig
259c259
<                 log.error("Unknown plot type {plot_type}. Ignored")
---
>                 log.error(f"Unknown plot type {plot_type}. Ignored")
```

**Comment by tkeffer** [comment]
Thanks for reporting this.

Somehow a Python "f-string" snuck into V4.10.1. They will only work with Python 3.7 or later.

Fixed in commit https://github.com/weewx/weewx/commit/dbe8b59600da01c69350c3c223b6b5684c677db3
