### ISSUE TITLE
How to disable writing to a database

### ISSUE THREAD

**Issue by bibermann** [weewx/weewx#851]
I would like to have the possibility to disable writing to any database, to safe resources on my Raspberry Pi. I only want to send the data to a MQTT broker.

This is not documented.

I tried several things, commenting out various DB related things, but then I get other errors.

**Comment by tkeffer** [comment]
Unfortunately, you must have a database. It's needed for certain calculations, such as barometric pressure or rain rate.

Warren's suggestion is the best.

But, you shouldn't worry about the RPi. It can easily handle the load. I have WeeWX running on an antique RPi model B without any problems.
