### ISSUE TITLE
how to control logging?

### ISSUE THREAD

**Issue by W11T** [weewx/weewx#860]
Sorry, this is rather a question than an issue.
I'm using the extension bme280wx in version 1.0 and i find all of these messages every ~ 15 seconds in all of user.log syslog debug messages:

... weewxd: bme280: {'outHumidity': 99.0, 'outTemp': 9.1, ...
... weewxd: bme280: BME280 data compensated_reading(id=...

Off cource this is filling my /var/log filesystem every couple of days.

I followed the advice in [How to limit syslog logging](https://www.mail-archive.com/weewx-user@googlegroups.com/msg33586.htmlhttps://www.mail-archive.com/weewx-user@googlegroups.com/msg33586.html) which didn't help much.

How can i control in which file theses messages are logged?

**Comment by tkeffer** [comment]
Please direct general support questions to [weewx-user](https://groups.google.com/g/weewx-user).

The issues list is for bug reporting and tracking.
