### ISSUE TITLE
Which Template(s) to Edit?

### ISSUE THREAD

**Issue by skierinavon** [weewx/weewx#865]
Please see attached screen shot from Weewx main   index.html
At Issue:  My WeatherFlow/Tempest does not report "inside Temp and Humidity"

Q.)  What templates do I edit to remove the reference to that?  See attached JPG
![Template-to-Edit](https://user-images.githubusercontent.com/4268815/231242924-7ba6d095-4e43-4d11-87ad-62579cd5571c.JPG)

**Comment by skierinavon** [comment]
Found the Answer.
You need to edit skins.conf  located in  /etc/weewx/skins/Seasons
Just eliminate the reference to those fields and plots...

**Comment by gjr80** [comment]
Correct. Just for future reference this issue list is for WeeWX bug tracking only. Please post future support requests to the [weewx-user Google group](https://groups.google.com/g/weewx-user).
