### ISSUE TITLE
Set locale when using internationalized skins

### ISSUE THREAD

**Issue by tkeffer** [weewx/weewx#867]
Right now, we depend on the user setting the `LOCALE` environment variable before running reports. This works, but it means all reports use the same locale.

Alternatively, we could optionally set the locale within the program before running each report.

``` python
import locale
...
locale.setlocale(locale.LC_ALL, 'es_ES')
```

Unfortunately, the locale used in `setlocale()` requires a country code as well as a language code, so we can't use option `lang` in `skin.conf` (which is only a language code). So, we need to either add a country code to `lang`, or we need another option `locale`.

**Comment by tkeffer** [comment]
Implemented in commit https://github.com/weewx/weewx/commit/bbaf514fe8c3d1692cc759620e7ea00d66ef0225

**Comment by mKainzbauer** [comment]
Yes! 😀

**Comment by tkeffer** [comment]
Glad you like it!

See [_Changing languages_](https://github.com/weewx/weewx/blob/development/docs_src/custom/custom-reports.md#changing-languages) for how it works.
