### ISSUE TITLE
Incorrect use of "Radiation"

### ISSUE THREAD

**Issue by wwortel** [weewx/weewx#873]
'Radiation' is the notion of some source emitting waves and/or particles. Meant in the context of weather stations and reporting is 'Irradiance', a certain amount of sun rays incident on a surface, quantified as energy per time and per unit of area [W.s-1.m-2].
So the correct label and caption should be 'Irradiance',  not 'Radiation'.

**Comment by tkeffer** [comment]
While you are correct, the term in this context is from the [Davis documentation](https://cdn.shopify.com/s/files/1/0515/5992/3873/files/VantageSerialProtocolDocs_v261.pdf?v=1614399559), where they call the output of their sensor simply "radiation." In any case, it is super easy to change it to anything you want.

You are also welcome to submit a PR, with the necessary changes.

Incidentally, Watts is a measure of power, not energy, so it's W/m².
