### ISSUE TITLE
Wrong comparison for stale temperature value?

### ISSUE THREAD

**Issue by roe-dl** [weewx/weewx#875]
https://github.com/weewx/weewx/blob/548bf5eccc5bba35eeefe482fe4fd1b95f364f06/bin/weewx/wxxtypes.py#L387

Am I right if I assume that there should be greater-than instead of less-than? 

The re-calculation is done if the condition is true. And the value is stale if the time difference is bigger than the limit.

See https://github.com/weewx/weewx/pull/874

**Comment by tkeffer** [comment]
Yes, you are right.

Fixed in commit https://github.com/weewx/weewx/commit/d3294cccf7c37da1485a068e4d6f8cc460703bdb
