### ISSUE TITLE
weewx netatmo driver 

### ISSUE THREAD

**Issue by odo125** [weewx/weewx#878]
Hi my netatmo-driver don't work anymore since 11th of July 2023. 
I think something on the netatmo api has changed. I get the following error:

"netatmo: netatmo-client: failed attempt 1 of 5 to get data: HTTP Error 400
netatmo: netatmo-client: url: https://api.netatmo.net/oauth2/token data: b'grant_type=password&client_id=64146554164654464554654&client_secret=456545465464644654874841579874468&username=........................."
(client_id and client_secret was changed by me in this posting)

Maybee "grant_type=password" is not allowed anymore.
Can you tell me if this can get fixed. Thanks in advance.

**Comment by tkeffer** [comment]
My apologies, but netatmo is not one of the supported WeeWX drivers. You'll have to ask the author.
