### ISSUE TITLE
Updated Humidex Formula Environment Canada - wxformulas.py

### ISSUE THREAD

**Issue by chrisale** [weewx/weewx#883]
I noticed today that weewx's docs for Humidex are a little out of date. The referenced website in wxformulas is 404. Environment Canada has updated the Humidex formula and the website.
New Web Reference: https://www.canada.ca/en/environment-climate-change/services/climate-change/canadian-centre-climate-services/display-download/technical-documentation-hourly-data.html

Formula corrections:
exp = 2.71828
Change 1/273.16 to 1/273.15
Also: Environment Canada does not make any indication that the resulting Humidex value can be accurately converted from Celsius to Fahrenheit. Weewx converting it to Fahrenheit may not be a valid Index.

Full Formula from Environment Canada's reference linked above:

"The standard Humidex formula used by Environment and Climate Change Canada is:

Humidex = (air temperature) + h

Where
h = (0.5555)*(e – 10.0);
e = vapour pressure in hPa (mbar), given by:
e = 6.11 * exp[5417.7530 * ( (1/273.15) – (1/dewpoint) ) ]
exp = 2.71828

Dewpoint is expressed in kelvins(K) (temperature in K = temperature in °C + 273.15) and 5417.7530 is a rounded constant based on the molecular weight of water, latent heat of evaporation, and the universal gas constant."

**Comment by tkeffer** [comment]
I've corrected the reference and formula.

Commit https://github.com/weewx/weewx/commit/a6c169fd65d851713e89913478191d461c6a1b25
