### ISSUE TITLE
In Pillow 10.0.0 Image.ANTIALIAS is replaced with Image.LANCZOS or Image.Resampling.LANCZO

### ISSUE THREAD

**Issue by bellrichm** [weewx/weewx#884]
FYI, it looks like there is some more refactoring in Pillow 10.0.0. Here is some additional information:
https://stackoverflow.com/questions/76616042/attributeerror-module-pil-image-has-no-attribute-antialias
https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#constants

And where WeeWX uses the constant, 
```
if self.anti_alias != 1:
            image.thumbnail((self.image_width / self.anti_alias, self.image_height / self.anti_alias), Image.ANTIALIAS)
```

**Comment by tkeffer** [comment]
Thanks for spotting that.

Fixed in commit https://github.com/weewx/weewx/commit/2482eebf8a35a6ddbd3cc9af01e98fde0910e345

Breaking lots of stuff in their zeal to make Python look like Java.
