### ISSUE TITLE
changing case of example Basic skin causes problems on weectl create station

### ISSUE THREAD

**Issue by bmusat** [weewx/weewx#888]
After using `weectl station create` there are two folders in the example skins directory. One called “basic” and one called “Basic”.  I do not think the case-sensitivity is consistent throughout the whole code base which causes the two directory problem. This will be problematic with Windows and MacOS file systems which don’t allow directories of the same name but with different cases. 

I stumbled upon this while trying to bind mount a linux container to a MacOS directory.

**Comment by tkeffer** [comment]
Thanks for spotting this. It's an artifact of not cleaning the distribution directory before starting the final build.
