### ISSUE TITLE
Special characters in de.conf

### ISSUE THREAD

**Issue by ManfredK1968** [weewx/weewx#891]
Hello,
If you use the special characters in the corresponding HTML code in de.conf (`ö`-->`&ouml;`), in images (png) the text is incorrectly in images (24h, week, month and year) (e.g. instead of `Böen` `B&ouml;en` is written).

**Comment by tkeffer** [comment]
Thanks for your note.

I'm sorry, but I'm not seeing the difference. At least, on my browser, 'Böen' and 'Böen' look identical.

**Comment by ManfredK1968** [comment]
Hello,
Look here:
https://bootstrap.wetter-ruppersthal.at/day.html#graphMenu

**Comment by roe-dl** [comment]
I guess if it is HTML both UTF-8-`ö` and HTML-`&ouml;` are equivalent. But for creating diagrams, UTF-8 characters are recognized only.

**Comment by tkeffer** [comment]
Ah, now I understand!

It displays correctly using the Seasons skin.

![image](https://github.com/weewx/weewx/assets/3321259/84539cef-425e-4c8c-8c21-b701b29b46aa)

Which skin are you using?

**Comment by ManfredK1968** [comment]
Oh sorry I use the bootstrap skin.
