### ISSUE TITLE
Reliable import project from wunderground in real time

### ISSUE THREAD

**Issue by Sylvain-27** [weewx/weewx#894]
Is there a reliable import project from wunderground in real time to store it in a mysql weewx database that has been carried out?
Is there a dedicated extension?

Testimonies of the erasure of the wunderground base encourage caution.

**Comment by tkeffer** [comment]
I am not aware of any such extension. You'd have to put it together yourself.

**Comment by Sylvain-27** [comment]
Ok thank you.
I'm not a developer and not very comfortable with field mapping.
That was the reason for my question.
I'll try.
