### ISSUE TITLE
weectl extension list returns 'No extensions installed' under some circumstances

### ISSUE THREAD

**Issue by vinceskahan** [weewx/weewx#909]
This one is minor to say the least but I thought I'd submit it....

(background)
Recall that the current 5.0rcN version string blows up strict version checking that is used in some of the usual extensions including gw1000 and xaggs to name two.   The result is that running 'weectl extension list' blows up and halts when that happens when it reaches the first such extension that uses Strict version checking.

Matthew provided a workaround for the 5.0rcN timeframe saying to temporarily edit those install.py files to a simple "if False:" to disable their strict version checking.  Workaround works fine as a temporary solution until weewx goes back to using python's strict version strings.

I made the needed edits here,  but I wanted to also leave a trail so I remembered that I'd hacked on the installed extensions so that I could revert the (temporary) changes when 5.0.0 releases and the workaround is no longer needed.

So I dropped a README.first file in bin/user/installer to hopefully remind myself.

(the bug)

If you put a simple text file in bin/user/installer then 'weectl extension list' reports no extensions found even though they are of course there.   It seems extension.py makes assumptions that nobody will add unexpected files/directories under the hood there.

(suggested result)

The 'weectl extension list' command should simply ignore anything in bin/user/installer that is not a directory with an underlying install.py file that passes muster.

(possible fix)

I wrappered the existing code in extension.py around line 78 with the following:

````
                for f in exts:
                    try:
                       info = self.get_extension_info(f)
                       msg = "%(name)-18s%(version)-10s%(description)s" % info
                       self.printer.out(msg, level=0)
                    except:
                        pass
````

Again - this one is a 'very' nit thing.  No need to block any weewx releases for this one, but opening it here in case somebody else runs into it.   I didn't do exhaustive fiddling to see if the try/except above caused other features to appear, but it might be worth considering.

**Comment by tkeffer** [comment]
Fixed. Now prints something like this:

```
python3 -m weectl extension list
Using configuration file /Users/tkeffer/weewx-data/weewx.conf
Extension Name    Version   Description
junk              ???       Cannot find 'install' module in /Users/tkeffer/weewx-data/bin/user/installer/junk
windy             0.7       Upload weather data to Windy.
```
