### ISSUE TITLE
permit meteorological days other than midnight-to-midnight

### ISSUE THREAD

**Issue by matthewwall** [weewx/weewx#91]
for example, france uses 07:00, india uses 08:30, UK uses 09:00

see https://groups.google.com/forum/#!topic/weewx-user/kcblP3PUwU8

**Comment by morrowwm** [comment]
Interesting idea. Natural gas utilities in North America use a mid-morning day boundary. Their operations are weather sensitive, and so they prefer meteorological dailies aligned with their operational day boundaries. Electrical utilities have a midnight boundary. There has been talk about aligning the two segments (https://www.aga.org/federal-regulatory-issues-and-advocacy/north-american-energy-standards-board) but it may not make sense.

**Comment by evilbunny2008** [comment]
I wanted to do something similar to be able to compare local rain fall before/since 9am with Australian data, Gary is responsible for 99% of the code, I just extended it a little to do before 9am and added a minute option.

[since.py.txt](https://github.com/weewx/weewx/files/2082668/since.py.txt)

Hopefully it's helpful to others as well.

**Comment by spacelama** [comment]
> I wanted to do something similar to be able to compare local rain fall before/since 9am with Australian data, Gary is responsible for 99% of the code, I just extended it a little to do before 9am and added a minute option.

evilbunny2008, last time I looked at this code, it lacked any context of how to use it - how to import it, how to call it from a template etc.  Do you have a pointer to docs for it?

**Comment by evilbunny2008** [comment]
To get the rain since 9am you'd do the following.

$since($hour=9).rain.sum.formatted

**Comment by roe-dl** [comment]
See [weewx-GTS special time spans](https://github.com/roe-dl/weewx-GTS#special-time-spans)
