### ISSUE TITLE
`weecfg device` wrongly reports no configuration file when it finds the default

### ISSUE THREAD

**Issue by marriotb** [weewx/weewx#921]
The command `weecfg device` with no `--config=` argument reports: 

> Using configuration file **None**

when in fact it does find '~/weewx-data/weewx.conf'.

Using Weewx 5.0.1 direct from the GitHub repo.

I've verified that the config is actually read by printing out the dict.

It looks like there's a confusion in `device_actions.py` between the variables `config_path` and `config_fn`.

Cheers
Brian

**Comment by tkeffer** [comment]
Thanks for spotting that!
