### ISSUE TITLE
including new instruments

### ISSUE THREAD

**Issue by bread-on-toast** [weewx/weewx#938]
Hi all,
I am trying to figure out if it is possible to include other measuring devices. I am measuring roadside immissions, so it would be interesting for me to include eg a Teledyne T200 or other of my instruments. Is there some guide on how to do that or where to start coding?

**Comment by tkeffer** [comment]
Mr. Bread,

The issues list is for tracking bugs in WeeWX. Instead, I would encourage you to post on the [weewx-user](https://groups.google.com/g/weewx-user) group. You're more likely to get a response there.
