### ISSUE TITLE
[Fix pending] Upgrades broken on Fedora due to epel-release dependency

### ISSUE THREAD

**Issue by funnelfiasco** [weewx/weewx#940]
Upgrades to version 5.0.2 are broken on Fedora because of the dependency on the _epel-release_ package introduced in fdbaafc. Fedora does not have an epel-release package because it's not an enterprise Linux.

Commit 8672a54 should fix this, but that's not yet in a released version. I'm opening this for visibility.

**Comment by matthewwall** [comment]
sorry that the removal of epel-release as a dependency got thrown in with other changes.  i thought i would have a 5.0.3 out quickly, but there are a few more changes and testing to do.

**Comment by funnelfiasco** [comment]
Just updated to v5.1.0b4 and I can confirm that the upgrade path that was broken is now fixed. :-)
