### ISSUE TITLE
Reopen  #247

### ISSUE THREAD

**Issue by ps-crawford** [weewx/weewx#945]
It seems issue  #247 (where Vantange data import fails on DST transition) has been closed. I don't know why because it has not been fixed.

Furthermore, the work-around for it now seems broken as the wee_device command no longer seems to exist in 5.x.x

**Comment by tkeffer** [comment]
Reopening this issue under another name won't change the underlying facts. This is a problem with the Vantage stations. The only fix is to use software record generation.
