### ISSUE TITLE
Add RSync options capability - exclude files/directories

### ISSUE THREAD

**Issue by chrisale** [weewx/weewx#951]
Hi there,

The actual functionality I'm looking for is the ability to exclude a file or directory from the rsync report so that if a file exists on the local weewx side within the weewx htmlroot but it is subsequently updated on the remote side by other means, then weewx does not overwrite those files/folders on the next rsync update interval.

This is related to this discussion on the google group:
https://groups.google.com/g/weewx-user/c/1BE0DCfU1nk/m/Di86nu-fAQAJ

It was suggested in that discussion that an "rsync_options" configuration to the RSYNC stanza that could include any potential rsync options supported by the underlying system would address this problem and give other potential benefits though there are unknown security implications as well.

Thanks for your time
Chris

**Comment by tkeffer** [comment]
I ended up using `rsync_options`. Now you can say something like

    rsync_options = --exclude=*.ts, --ipv6

To appear in V5.1
