### ISSUE TITLE
v4 setup to v5 pip instructions are missing a step

### ISSUE THREAD

**Issue by vinceskahan** [weewx/weewx#960]
https://github.com/weewx/weewx/wiki/v5-upgrade is missing a step between (1) and (2) of the Migration Process.

When upgrading from v4 setup to v5 pip, the result will have the venv installed into $HOME of the non-privileged user that runs the pip command, but the weewx-data contents are in the /home/weewx tree that was already present and owned by root:root, meaning that tree is not writable by a non-privileged user.

The missing step (1a) is to "`sudo chown -R pi:pi /home/weewx`" (using a pi user as an example).

**Comment by tkeffer** [comment]
Fixed with commit 1ae54f73
