### ISSUE TITLE
additional values

### ISSUE THREAD

**Issue by hoefler50** [weewx/weewx#967]
Hello, I have added a driver so that it can also read my electricity meter. After an update, I have to manually adjust the units.py again because I have additional types. I found the place in the instructions, but I can't get it to work. Do any of you know of a driver that also uses the values ​​from the energy group? best regards Michael

**Comment by tkeffer** [comment]
Hello,

Please direct your question to [weewx-user](https://groups.google.com/g/weewx-user). The issues list is for bug reporting and tracking.

Having said that, if you look through the [drivers](https://github.com/weewx/weewx/wiki#drivers) listed in the wiki, a few of them are for solar controllers. They may use energy values.
