### ISSUE TITLE
ERROR weewx.engine: Unable to shut down StdReport thread

### ISSUE THREAD

**Issue by Antyrael** [weewx/weewx#968]
Since the upgrade from 4.10.2 to 5.1.0 I'm seeing "database is locked" issues that never happened before.

I followed to upgrade instructions to the letter and things do appear to be working, because files are being updated and uploaded as configured in weewx.conf.
It would be nice though if this one recurring error could be fixed, but I don't know how.

Below is part of the logs that show the loop weewx appears to be in. Hopefully someone can help me solve this issue.

PS: you can ignore the StationRegistry error (at least, I don't think it has anything to do with the aforementioned issue).

> Jul 09 10:52:39 weather weewxd[973]: INFO __main__: retrying...
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.engine: Loading station type WMR100 (weewx.drivers.wmr100)
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.drivers.wmr100: Driver version is 3.5.0
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.drivers.wmr100: Sensor map is {'pressure': 'pressure', 'windSpeed': 'wind_speed', 'windDir': 'wind_dir', 'windGust': 'wind_gust', 'windBatteryStatus': 'battery_status_wind', 'inTemp': 'temperature_0', 'outTemp': 'temperature_1', 'extraTemp1': 'temperature_2', 'extraTemp2': 'temperature_3', 'extraTemp3': 'temperature_4', 'extraTemp4': 'temperature_5', 'extraTemp5': 'temperature_6', 'extraTemp6': 'temperature_7', 'extraTemp7': 'temperature_8', 'inHumidity': 'humidity_0', 'outHumidity': 'humidity_1', 'extraHumid1': 'humidity_2', 'extraHumid2': 'humidity_3', 'extraHumid3': 'humidity_4', 'extraHumid4': 'humidity_5', 'extraHumid5': 'humidity_6', 'extraHumid6': 'humidity_7', 'extraHumid7': 'humidity_8', 'inTempBatteryStatus': 'battery_status_0', 'outTempBatteryStatus': 'battery_status_1', 'extraBatteryStatus1': 'battery_status_2', 'extraBatteryStatus2': 'battery_status_3', 'extraBatteryStatus3': 'battery_status_4', 'extraBatteryStatus4': 'battery_status_5', 'extraBatteryStatus5': 'battery_status_6', 'extraBatteryStatus6': 'battery_status_7', 'extraBatteryStatus7': 'battery_status_8', 'rain': 'rain', 'rainTotal': 'rain_total', 'rainRate': 'rain_rate', 'hourRain': 'rain_hour', 'rain24': 'rain_24', 'rainBatteryStatus': 'battery_status_rain', 'UV': 'uv', 'uvBatteryStatus': 'battery_status_uv'}
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.engine: StdConvert target unit is 0x1
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.wxservices: StdWXCalculate will use data binding wx_binding
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.engine: Archive will use data binding wx_binding
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.engine: Record generation will be attempted in 'hardware'
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.engine: Using archive interval of 300 seconds (specified in weewx configuration)
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.restx: StationRegistry: Station will be registered.
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.restx: Wunderground-PWS: Data for station IOVERIJS199 will be posted
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.restx: PWSweather: Posting not enabled.
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.restx: CWOP: Posting not enabled.
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.restx: WOW: Posting not enabled.
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.restx: AWEKAS: Posting not enabled.
> Jul 09 10:52:39 weather weewxd[973]: INFO user.meteotemplate: service version is 0.10
> Jul 09 10:52:39 weather weewxd[973]: INFO user.meteotemplate: Data will be uploaded to https://weather.astrogallery.eu/api.php
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.engine: 'pyephem' detected, extended almanac data is available
> Jul 09 10:52:39 weather weewxd[973]: INFO __main__: Starting up weewx version 5.1.0
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.manager: Starting backfill of daily summaries
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.manager: Daily summaries up to date
> Jul 09 10:52:39 weather weewxd[973]: INFO weewx.engine: Starting main packet loop.
> Jul 09 10:55:22 weather weewxd[973]: INFO weewx.manager: Added record 2024-07-09 10:55:00 CEST (1720515300) to database 'weewx.sdb'
> Jul 09 10:55:22 weather weewxd[973]: INFO weewx.manager: Added record 2024-07-09 10:55:00 CEST (1720515300) to daily summary in 'weewx.sdb'
> Jul 09 10:55:23 weather weewxd[973]: INFO weewx.restx: Wunderground-PWS: Published record 2024-07-09 10:55:00 CEST (1720515300)
> Jul 09 10:55:23 weather weewxd[973]: INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 1.12 seconds
> Jul 09 10:55:24 weather weewxd[973]: INFO weewx.imagegenerator: Generated 15 images for report SeasonsReport in 0.59 seconds
> Jul 09 10:55:24 weather weewxd[973]: INFO weewx.reportengine: Copied 5 files to /opt/weewx/public_html
> Jul 09 10:56:02 weather weewxd[973]: ERROR weewx.restx: StationRegistry: Failed to publish record 2024-07-09 10:55:00 CEST (1720515300): HTTP Error 429: TOO MANY REQUESTS
> Jul 09 11:00:24 weather weewxd[973]: INFO weewx.manager: Added record 2024-07-09 11:00:00 CEST (1720515600) to database 'weewx.sdb'
> Jul 09 11:00:24 weather weewxd[973]: INFO weewx.manager: Added record 2024-07-09 11:00:00 CEST (1720515600) to daily summary in 'weewx.sdb'
> Jul 09 11:00:29 weather weewxd[973]: INFO weewx.engine: Main loop exiting. Shutting engine down.
> Jul 09 11:00:29 weather weewxd[973]: INFO weewx.engine: Shutting down StdReport thread
### > Jul 09 11:00:49 weather weewxd[973]: CRITICAL __main__:     ****  Waiting 2 minutes then retrying...
> Jul 09 11:00:50 weather weewxd[973]: INFO weewx.cheetahgenerator: Generated 12 files for report StandardReport in 326.15 seconds
> Jul 09 11:00:50 weather weewxd[973]: INFO weewx.reportengine: Copied 39 files to /opt/weewx/public_html
> Jul 09 11:00:52 weather weewxd[973]: INFO weewx.cheetahgenerator: Generated 14 files for report Standard in 0.90 seconds
> Jul 09 11:00:52 weather weewxd[973]: INFO weewx.imagegenerator: Generated 12 images for report Standard in 0.35 seconds
> Jul 09 11:00:52 weather weewxd[973]: INFO weewx.reportengine: Copied 14 files to /opt/weewx/public_html/standard
> Jul 09 11:00:53 weather weewxd[973]: INFO weewx.cheetahgenerator: Generated 1 files for report Inigo in 0.22 seconds
> Jul 09 11:00:54 weather weewxd[973]: INFO weeutil.rsyncupload: rsync'd 122 files (1,893,760 bytes) in 1.35 seconds
> Jul 09 11:02:49 weather weewxd[973]: INFO __main__: retrying...
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.engine: Loading station type WMR100 (weewx.drivers.wmr100)
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.drivers.wmr100: Driver version is 3.5.0
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.drivers.wmr100: Sensor map is {'pressure': 'pressure', 'windSpeed': 'wind_speed', 'windDir': 'wind_dir', 'windGust': 'wind_gust', 'windBatteryStatus': 'battery_status_wind', 'inTemp': 'temperature_0', 'outTemp': 'temperature_1', 'extraTemp1': 'temperature_2', 'extraTemp2': 'temperature_3', 'extraTemp3': 'temperature_4', 'extraTemp4': 'temperature_5', 'extraTemp5': 'temperature_6', 'extraTemp6': 'temperature_7', 'extraTemp7': 'temperature_8', 'inHumidity': 'humidity_0', 'outHumidity': 'humidity_1', 'extraHumid1': 'humidity_2', 'extraHumid2': 'humidity_3', 'extraHumid3': 'humidity_4', 'extraHumid4': 'humidity_5', 'extraHumid5': 'humidity_6', 'extraHumid6': 'humidity_7', 'extraHumid7': 'humidity_8', 'inTempBatteryStatus': 'battery_status_0', 'outTempBatteryStatus': 'battery_status_1', 'extraBatteryStatus1': 'battery_status_2', 'extraBatteryStatus2': 'battery_status_3', 'extraBatteryStatus3': 'battery_status_4', 'extraBatteryStatus4': 'battery_status_5', 'extraBatteryStatus5': 'battery_status_6', 'extraBatteryStatus6': 'battery_status_7', 'extraBatteryStatus7': 'battery_status_8', 'rain': 'rain', 'rainTotal': 'rain_total', 'rainRate': 'rain_rate', 'hourRain': 'rain_hour', 'rain24': 'rain_24', 'rainBatteryStatus': 'battery_status_rain', 'UV': 'uv', 'uvBatteryStatus': 'battery_status_uv'}
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.engine: StdConvert target unit is 0x1
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.wxservices: StdWXCalculate will use data binding wx_binding
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.engine: Archive will use data binding wx_binding
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.engine: Record generation will be attempted in 'hardware'
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.engine: Using archive interval of 300 seconds (specified in weewx configuration)
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.restx: StationRegistry: Station will be registered.
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.restx: Wunderground-PWS: Data for station IOVERIJS199 will be posted
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.restx: PWSweather: Posting not enabled.
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.restx: CWOP: Posting not enabled.
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.restx: WOW: Posting not enabled.
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.restx: AWEKAS: Posting not enabled.
> Jul 09 11:02:49 weather weewxd[973]: INFO user.meteotemplate: service version is 0.10
> Jul 09 11:02:49 weather weewxd[973]: INFO user.meteotemplate: Data will be uploaded to https://weather.astrogallery.eu/api.php
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.engine: 'pyephem' detected, extended almanac data is available
> Jul 09 11:02:49 weather weewxd[973]: INFO __main__: Starting up weewx version 5.1.0
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.manager: Starting backfill of daily summaries
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.manager: Daily summaries up to date
> Jul 09 11:02:49 weather weewxd[973]: INFO weewx.engine: Starting main packet loop.
> Jul 09 11:05:14 weather weewxd[973]: INFO weewx.manager: Added record 2024-07-09 11:05:00 CEST (1720515900) to database 'weewx.sdb'
> Jul 09 11:05:14 weather weewxd[973]: INFO weewx.manager: Added record 2024-07-09 11:05:00 CEST (1720515900) to daily summary in 'weewx.sdb'
> Jul 09 11:05:15 weather weewxd[973]: INFO weewx.restx: Wunderground-PWS: Published record 2024-07-09 11:05:00 CEST (1720515900)
> Jul 09 11:05:16 weather weewxd[973]: INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 1.14 seconds
> Jul 09 11:05:16 weather weewxd[973]: INFO weewx.imagegenerator: Generated 15 images for report SeasonsReport in 0.59 seconds
> Jul 09 11:05:16 weather weewxd[973]: INFO weewx.reportengine: Copied 5 files to /opt/weewx/public_html
> Jul 09 11:05:38 weather weewxd[973]: ERROR weewx.restx: StationRegistry: Failed to publish record 2024-07-09 11:05:00 CEST (1720515900): HTTP Error 429: TOO MANY REQUESTS
> Jul 09 11:10:22 weather weewxd[973]: INFO weewx.manager: Added record 2024-07-09 11:10:00 CEST (1720516200) to database 'weewx.sdb'
> Jul 09 11:10:22 weather weewxd[973]: INFO weewx.manager: Added record 2024-07-09 11:10:00 CEST (1720516200) to daily summary in 'weewx.sdb'
> Jul 09 11:10:27 weather weewxd[973]: INFO weewx.engine: Main loop exiting. Shutting engine down.
> Jul 09 11:10:27 weather weewxd[973]: INFO weewx.engine: Shutting down StdReport thread
### > Jul 09 11:10:47 weather weewxd[973]: CRITICAL __main__:     ****  Waiting 2 minutes then retrying...
> Jul 09 11:10:48 weather weewxd[973]: INFO weewx.cheetahgenerator: Generated 12 files for report StandardReport in 331.82 seconds
> Jul 09 11:10:48 weather weewxd[973]: INFO weewx.reportengine: Copied 39 files to /opt/weewx/public_html
> Jul 09 11:10:50 weather weewxd[973]: INFO weewx.cheetahgenerator: Generated 14 files for report Standard in 0.90 seconds
> Jul 09 11:10:50 weather weewxd[973]: INFO weewx.imagegenerator: Generated 12 images for report Standard in 0.35 seconds
> Jul 09 11:10:50 weather weewxd[973]: INFO weewx.reportengine: Copied 14 files to /opt/weewx/public_html/standard
> Jul 09 11:10:51 weather weewxd[973]: INFO weewx.cheetahgenerator: Generated 1 files for report Inigo in 0.22 seconds
> Jul 09 11:10:52 weather weewxd[973]: INFO weeutil.rsyncupload: rsync'd 122 files (1,895,033 bytes) in 1.17 seconds
> Jul 09 11:12:47 weather weewxd[973]: INFO __main__: retrying...
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.engine: Loading station type WMR100 (weewx.drivers.wmr100)
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.drivers.wmr100: Driver version is 3.5.0
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.drivers.wmr100: Sensor map is {'pressure': 'pressure', 'windSpeed': 'wind_speed', 'windDir': 'wind_dir', 'windGust': 'wind_gust', 'windBatteryStatus': 'battery_status_wind', 'inTemp': 'temperature_0', 'outTemp': 'temperature_1', 'extraTemp1': 'temperature_2', 'extraTemp2': 'temperature_3', 'extraTemp3': 'temperature_4', 'extraTemp4': 'temperature_5', 'extraTemp5': 'temperature_6', 'extraTemp6': 'temperature_7', 'extraTemp7': 'temperature_8', 'inHumidity': 'humidity_0', 'outHumidity': 'humidity_1', 'extraHumid1': 'humidity_2', 'extraHumid2': 'humidity_3', 'extraHumid3': 'humidity_4', 'extraHumid4': 'humidity_5', 'extraHumid5': 'humidity_6', 'extraHumid6': 'humidity_7', 'extraHumid7': 'humidity_8', 'inTempBatteryStatus': 'battery_status_0', 'outTempBatteryStatus': 'battery_status_1', 'extraBatteryStatus1': 'battery_status_2', 'extraBatteryStatus2': 'battery_status_3', 'extraBatteryStatus3': 'battery_status_4', 'extraBatteryStatus4': 'battery_status_5', 'extraBatteryStatus5': 'battery_status_6', 'extraBatteryStatus6': 'battery_status_7', 'extraBatteryStatus7': 'battery_status_8', 'rain': 'rain', 'rainTotal': 'rain_total', 'rainRate': 'rain_rate', 'hourRain': 'rain_hour', 'rain24': 'rain_24', 'rainBatteryStatus': 'battery_status_rain', 'UV': 'uv', 'uvBatteryStatus': 'battery_status_uv'}
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.engine: StdConvert target unit is 0x1
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.wxservices: StdWXCalculate will use data binding wx_binding
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.engine: Archive will use data binding wx_binding
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.engine: Record generation will be attempted in 'hardware'
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.engine: Using archive interval of 300 seconds (specified in weewx configuration)
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.restx: StationRegistry: Station will be registered.
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.restx: Wunderground-PWS: Data for station IOVERIJS199 will be posted
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.restx: PWSweather: Posting not enabled.
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.restx: CWOP: Posting not enabled.
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.restx: WOW: Posting not enabled.
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.restx: AWEKAS: Posting not enabled.
> Jul 09 11:12:47 weather weewxd[973]: INFO user.meteotemplate: service version is 0.10
> Jul 09 11:12:47 weather weewxd[973]: INFO user.meteotemplate: Data will be uploaded to https://weather.astrogallery.eu/api.php
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.engine: 'pyephem' detected, extended almanac data is available
> Jul 09 11:12:47 weather weewxd[973]: INFO __main__: Starting up weewx version 5.1.0
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.engine: Using binding 'wx_binding' to database 'weewx.sdb'
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.manager: Starting backfill of daily summaries
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.manager: Daily summaries up to date
> Jul 09 11:12:47 weather weewxd[973]: INFO weewx.engine: Starting main packet loop.
> Jul 09 11:15:22 weather weewxd[973]: INFO weewx.manager: Added record 2024-07-09 11:15:00 CEST (1720516500) to database 'weewx.sdb'
> Jul 09 11:15:22 weather weewxd[973]: INFO weewx.manager: Added record 2024-07-09 11:15:00 CEST (1720516500) to daily summary in 'weewx.sdb'
> Jul 09 11:15:23 weather weewxd[973]: INFO weewx.restx: Wunderground-PWS: Published record 2024-07-09 11:15:00 CEST (1720516500)
> Jul 09 11:15:23 weather weewxd[973]: ERROR weewx.restx: StationRegistry: Failed to publish record 2024-07-09 11:15:00 CEST (1720516500): HTTP Error 429: TOO MANY REQUESTS
> Jul 09 11:15:23 weather weewxd[973]: INFO weewx.cheetahgenerator: Generated 8 files for report SeasonsReport in 1.13 seconds
> Jul 09 11:15:24 weather weewxd[973]: INFO weewx.imagegenerator: Generated 15 images for report SeasonsReport in 0.65 seconds
> Jul 09 11:15:24 weather weewxd[973]: INFO weewx.reportengine: Copied 5 files to /opt/weewx/public_html
> Jul 09 11:20:24 weather weewxd[973]: INFO weewx.manager: Added record 2024-07-09 11:20:00 CEST (1720516800) to database 'weewx.sdb'
> Jul 09 11:20:24 weather weewxd[973]: INFO weewx.manager: Added record 2024-07-09 11:20:00 CEST (1720516800) to daily summary in 'weewx.sdb'
> Jul 09 11:20:29 weather weewxd[973]: INFO weewx.engine: Main loop exiting. Shutting engine down.
> Jul 09 11:20:29 weather weewxd[973]: INFO weewx.engine: Shutting down StdReport thread
### > Jul 09 11:20:49 weather weewxd[973]: CRITICAL __main__:     ****  Waiting 2 minutes then retrying...
> Jul 09 11:20:50 weather weewxd[973]: INFO weewx.cheetahgenerator: Generated 12 files for report StandardReport in 326.01 seconds
> Jul 09 11:20:50 weather weewxd[973]: INFO weewx.reportengine: Copied 39 files to /opt/weewx/public_html
> Jul 09 11:20:52 weather weewxd[973]: INFO weewx.cheetahgenerator: Generated 14 files for report Standard in 0.91 seconds
> Jul 09 11:20:52 weather weewxd[973]: INFO weewx.imagegenerator: Generated 12 images for report Standard in 0.35 seconds
> Jul 09 11:20:52 weather weewxd[973]: INFO weewx.reportengine: Copied 14 files to /opt/weewx/public_html/standard
> Jul 09 11:20:53 weather weewxd[973]: INFO weewx.cheetahgenerator: Generated 1 files for report Inigo in 0.22 seconds
> Jul 09 11:20:54 weather weewxd[973]: INFO weeutil.rsyncupload: rsync'd 122 files (1,897,726 bytes) in 1.39 seconds

**Comment by tkeffer** [comment]
I think what's happening is that running the reports is taking so long that
the old report has not finished by the time the new report needs to be run.
So, the two threads compete with each other for the database.

V5.0 allows the calculation of aggregates of derived types, which can take
a long time. In particular, the Belchertown skin asks for aggregates of
appTemp, which, depending on what database schema you are using, may or may
not be in the database and, therefore, may or may not have to be
calculated. There have been many threads about this.

See the wiki article Troubleshooting V5.x performance
<https://github.com/weewx/weewx/wiki/v5-performance-troubleshooting> for a
discussion and how to fix.

-tk

**Comment by Antyrael** [comment]
Thanks, this seems to be the solution to my problem indeed.
'weectl database calc-missing' is running now, over a total of 11 years of data, so it will be a while before I know for sure. But, I feel confident about this!

I did search for a solution before posting here, by the way, but I didn't find anything. Unfortunately I didn't stumble upon the article you mentioned, or the Belchertown github issue.

**Comment by tkeffer** [comment]
Didn’t mean to imply that you hadn’t done your research. Just that there’s
additional information available.

-tk
