### ISSUE TITLE
 "/etc/weewx/bin/user/crt.py", line 546, in handle_new_loop

### ISSUE THREAD

**Issue by G400** [weewx/weewx#970]
weewx 5.1.0 + crt 0.23

Yesterday crt stopped working with the traces shown below.
The strange thing is that it has been working for weeks without any issues and no updates or modifications to weewx or crt was done.

Aug 16 08:15:07 x.y.com weewxd[30136]:     self.dispatchEvent(weewx.Event(weewx.NEW_LOOP_PACKET, packet=packet))
Aug 16 08:15:07 x.y.com weewxd[30136]:   File "/usr/share/weewx/weewx/engine.py", line 241, in dispatchEvent
Aug 16 08:15:07 x.y.com weewxd[30136]:     callback(event)
Aug 16 08:15:07 x.y.com weewxd[30136]:   File "/etc/weewx/bin/user/crt.py", line 546, in handle_new_loop
Aug 16 08:15:07 x.y.com weewxd[30136]:     self.handle_data(event.packet)
Aug 16 08:15:07 x.y.com weewxd[30136]:   File "/etc/weewx/bin/user/crt.py", line 569, in handle_data
Aug 16 08:15:07 x.y.com weewxd[30136]:     traceback('crt: *** ')
Aug 16 08:15:07 x.y.com weewxd[30136]: TypeError: traceback() takes 0 positional arguments but 1 was given
Aug 16 08:15:07 x.y.com systemd[1]: weewx.service: Main process exited, code=exited, status=1/FAILURE
Aug 16 08:15:07 x.y.com systemd[1]: weewx.service: Failed with result 'exit-code'.

**Comment by tkeffer** [comment]
This is an issue with `crt`, not WeeWX. It appears that some kind of error occurred, but the code that handles the error has an error. In particular, `crt.py` line 16 reads

        traceback('crt: *** ')

when it should read

        traceback()

I would recomment filing an issue or PR on the [extension's GitHub page](https://github.com/matthewwall/weewx-crt).

Once this error gets fixed, it might be possible to see what the primary error is.
