### ISSUE TITLE
Where can I get a parameter list from Weewx?

### ISSUE THREAD

**Issue by bassemolufda** [weewx/weewx#973]
Hallo,

I would like to create a template for Weewx. To do this I need a template for how the data can be read out. For example:

`$current.outTemp.format(add_label=False)` for the value of the current temperature.

Can you help me?

Sincelery Uwe

**Comment by tkeffer** [comment]
The issues list is for bug reporting and tracking. For general support questions, please post to the [weewx-user](https://groups.google.com/g/weewx-user) mailing list.
