### ISSUE TITLE
FYI: weewx 5.1.0 on Debian 13 (trixie) - works

### ISSUE THREAD

**Issue by AhrBee** [weewx/weewx#975]
If there's any interest in futures: I have spare time so am running Debian testing release 13 `trixie` to see what stuff works and doesn't here, updated as of 2024-09-12. A plain vanilla installation of `weewx` 5.1.0 appears to be running just fine (output of `weectl debug --output=weewx-trixie.debug-info.txt` attached). `python3` version 3.12.x is installed. 

I did a new `pip` installation, added the `gw1000` and `mqtt` extensions, configured those, copied over my `weewx.sdb` database, restarted `weewx` - running along happily for a while without any errors thrown. The MQTT topic is being populated on the MQTT server. Graphs are generated identical to my production `weewx` installation. The `weewx.cheetahgenerator` and `weewx.imagegenerator` functions run in approximately the same elapsed time as in production.

Output of `weectl extension list`:
```
Using configuration file /home/weewx/weewx-data/weewx.conf
Extension Name    Version   Description
GW1000            0.6.3     WeeWX driver for devices using the Ecowitt LAN/Wi-Fi Gateway API.
mqtt              0.24      Upload weather data to MQTT server.
```

Output of `pip list`:
```
Package   Version
--------- -----------
configobj 5.0.8
CT3       3.3.3.post1
ephem     4.1.5
paho-mqtt 2.1.0
pillow    10.4.0
pip       24.2
PyMySQL   1.1.1
pyserial  3.5
pyusb     1.2.1
six       1.16.0
weewx     5.1.0
wheel     0.44.0

```

Did run into a minor issue installing `mqtt` extension that does not seem to affect operations:
```
/home/weewx/weewx-data/bin/user/mqtt.py:3: SyntaxWarning: invalid escape sequence '\-'
  """
```
I also changed the `mqtt` topic from the one in the attached debug info file. 

[weewx-trixie.debug-info.txt](https://github.com/user-attachments/files/16977496/weewx-trixie.debug-info.txt)

**Comment by tkeffer** [comment]
Good to know. Thanks for the report.
