### ISSUE TITLE
wee_extension not included anymore

### ISSUE THREAD

**Issue by pcossu61** [weewx/weewx#976]
I installed weewx about four years ago and everything worked perfectly.
in march I tried to implement mqtt and had to upgrade the whole system on dietpi on a Pine A64 hardware to the latest system.
unfortunately anything i tried to make things work again with bresser6in1 and rtl-sdr did not work anymore.
today i finally browsed the weewx docs and found the solution.
documents on weewx-sdr and most probably other extension still refer to the old wee-extension and mislead in their documents.

**Comment by tkeffer** [comment]
Unfortunately, there's nothing I can do about that. The documentation for `weewx-sdr` (and other extensions) is in the hands of the author. 

You can try filing an issue or, even better, a PR at the extension's GitHub page. For `weewx-sdr` that's here https://github.com/matthewwall/weewx-sdr/issues, although it looks like there's a huge backlog going back a couple of years.
