### ISSUE TITLE
Data Import

### ISSUE THREAD

**Issue by Sebeck81** [weewx/weewx#979]
Hi,

maybe someone can help me
I have installed weewx with the Belchertown skin. My weather station is currently sending the data to Wunderground and Awekas. At Wunderground I can fetch the data via API, unfortunately now every 5 minutes. At Awekas I also got an API, where I have 240 retrievals per minute. Unfortunately, it is not entirely clear to me how or whether it is even possible to adapt the import file. 

Maybe you still have an idea. 

Kind regards Sebastian

**Comment by tkeffer** [comment]
Hello,

The issues list is used to report and track bugs. I see that you have also posted to weewx-user. Let's focus the discussion there.
