### ISSUE TITLE
Reference / Units Page

### ISSUE THREAD

**Issue by David-Enst** [weewx/weewx#982]
The units table is messed up on this page (in all browsers):

https://weewx.com/docs/5.1/reference/units/

FYI,
Dave E

**Comment by tkeffer** [comment]
Thanks for your report.

What do you mean by "messed up?" It looks fine to me.

**Comment by David-Enst** [comment]
Here is what shows up for me, all browsers; the table is truncated on the right:

 



 

Cheers,

David Enstrom

**Comment by David-Enst** [comment]
Curious … image attached this time.

 

No, it cannot scroll!

 

 

Cheers,

David Enstrom

**Comment by tkeffer** [comment]
Still not seeing an image. Try posting directly to the issues list. 

https://github.com/weewx/weewx/issues/982

**Comment by tkeffer** [comment]
Yes, that's what it looks like until you scroll to the right. Look at the bottom of the table for the scroll bar. Is it there?

Or, if you're using a touchpad, two-finger scroll to the right.

**Comment by David-Enst** [comment]
OH! Just saw the scroll bar ... rather annoying, but sort of works. But you would have to scroll back and forth to actually see the whole row. :-\

**Comment by tkeffer** [comment]
Yes, you do. That's how MkDocs, the documentation software that we use, fits a wide table in a narrow screen. 

Frankly, I don't know how else it could be done.

Closing issue.
